### PR TITLE
Upgrading to UniFFI 0.24 [ci full]

### PR DESCRIPTION
**Pull request by bendk**
### Pull Request checklist ###

- **Breaking changes**:  This PR follows our [breaking change policy](https://github.com/mozilla/application-services/blob/main/docs/howtos/breaking-changes.md)
  - [ ] This PR follows the breaking change policy:
     - This PR has no breaking API changes, or
     - There are corresponding PRs for our consumer applications that resolve the breaking changes and have been approved
- [ ] **Quality**: This PR builds and tests run cleanly
  - Note:
    - For changes that need extra cross-platform testing, consider adding `[ci full]` to the PR title.
    - If this pull request includes a breaking change, consider [cutting a new release](https://github.com/mozilla/application-services/blob/main/docs/howtos/cut-a-new-release.md) after merging.
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes a changelog entry in [CHANGELOG.md](../CHANGELOG.md) or an explanation of why it does not need one
  - Any breaking changes to Swift or Kotlin binding APIs are noted explicitly
- [ ] **Dependencies**: This PR follows our [dependency management guidelines](https://github.com/mozilla/application-services/blob/main/docs/dependency-management.md)
  - Any new dependencies are accompanied by a summary of the due dilligence applied in selecting them.

[Branch builds](https://github.com/mozilla/application-services/blob/main/docs/howtos/branch-builds.md): add `[firefox-android: branch-name]` to the PR title.

### CODE REVIEW

**Comment by bendk** [comment]
Looks like this is working.  I think the plan should be to merge this alongside the Glean update that does the same.  Does that make sense to others?

**Comment by badboy** [comment]
Glean PR: https://github.com/mozilla/glean/pull/2510
m-c tracking: https://bugzilla.mozilla.org/show_bug.cgi?id=1840044

Note that we need: 
1. Glean & app-services release
2. m-c updates

Not sure if that will lead to issues with appservices nightly releases landing before any of the other work. I guess not, because the m-c part is separate anyway, right?

**Comment by bendk** [comment]
The Glean release has been out for a bit and we just switched to the 117 nightly cycle.  Seems like this is a good time to merge, any concerns?

The moz-central patch hasn't been approved, but that shouldn't block this.  In fact, I think we want to merge this into `main` first.

**Review by mhammond — APPROVED** [review]
I see no reason to be concerned

**Pull request merged**
