### PR TITLE
Use defaults from storageArea.get() despite an empty store

### PR DESCRIPTION
**Pull request by Rob--W**
Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1645598, by fixing the issue, adding a few clarifying comments and a few unit tests.

I didn't add a changelog because this patch should be merged with m-c, so I kept the changes at a minimum. I will send a separate PR for merging with the master branch.

### Pull Request checklist ###

- [ ] **Quality**: This PR builds and tests run cleanly
  - `automation/all_tests.sh` runs to completion and produces no failures
  - Note: For changes that need extra cross-platform testing, consider adding `[ci full]` to the PR title.
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes a changelog entry in [CHANGES_UNRELEASED.md](../CHANGES_UNRELEASED.md) or an explanation of why it does not need one
  - Any breaking changes to Swift or Kotlin binding APIs are noted explicitly
- [ ] **Dependencies**: This PR follows our [dependency management guidelines](https://github.com/mozilla/application-services/blob/master/docs/dependency-management.md)
  - Any new dependencies are accompanied by a summary of the due dilligence applied in selecting them.

### CODE REVIEW

**Comment by Rob--W** [comment]
CI complains about clippy, but that's an issue with #3207 (already fixed on master).

I'm going to cherry-pick #3207 to make the build green, but let me know if I should remove it.

**Comment by eoger** [comment]
@Mergifyio rebase

**Comment by Rob--W** [comment]
@eoger What are you trying to achieve with the "rebase" command? I'm not familiar with mergifyio, but if you're trying to rebase against master do note that this PR is supposed to be merged with vendor-mc/78, and that I cherry-picked a patch that is already on master to resolve a clippy CI failure.

**Comment by eoger** [comment]
Ha didn’t realize. Carry on then, my bad!

**Comment by linacambridge** [comment]
Also, thank you for submitting the PR against `master`—I was just about to ask if you wanted me to, but if you could, that would be wonderful!

**Comment by ljklllkhjkhjkgkj** [comment]
`app/src/main/AndroidManifest.xml`

**Pull request merged**
