### PR TITLE
Updating openssl-src (#4062)

### PR DESCRIPTION
**Pull request by bendk**
### Pull Request checklist ###

- [ ] **Quality**: This PR builds and tests run cleanly
  - Note:
    - Consider running `automation/all_tests.sh` to execute these tests locally.
    - For changes that need extra cross-platform testing, consider adding `[ci full]` to the PR title.
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes a changelog entry in [CHANGES_UNRELEASED.md](../CHANGES_UNRELEASED.md) or an explanation of why it does not need one
  - Any breaking changes to Swift or Kotlin binding APIs are noted explicitly
- [x] **Dependencies**: This PR follows our [dependency management guidelines](https://github.com/mozilla/application-services/blob/main/docs/dependency-management.md)
  - Any new dependencies are accompanied by a summary of the due dilligence applied in selecting them.

### CODE REVIEW

**Comment by grigoryk** [comment]
I don't think `Cargo.lock` should be edited manually - try to update Cargo.toml instead.

However, I'm not sure what we can change ourselves. Looking from the audit failure:
```
openssl-src 111.12.0+1.1.1h
└── openssl-sys 0.9.58
    ├── openssl 0.10.30
    │   └── native-tls 0.2.4
    │       ├── tokio-tls 0.3.1
    │       │   ├── reqwest 0.10.8
    │       │   │   └── viaduct-reqwest 0.1.0
...
```
we see that there isn't a direct dependency on openssl-src, it's getting pulled in via tokio-tls & reqwest.
Looking at `tokio-native-tls`''s dependencies, https://github.com/tokio-rs/tls/blob/master/tokio-native-tls/Cargo.toml#L40 - it depends on `openssl 0.10`, which for some reason doesn't seem like it's not picking up the latest 10.34 (https://github.com/sfackler/rust-openssl/releases) - I assume that would have pulled in the latest version of `openssl-src`...

Can we overwrite parts of the dependency graph w/ cargo? I'm not sure actually, can't find that in the docs.

**Comment by mhammond** [comment]
Yeah, I had a quick look earlier in the week and came to the same conclusion - it's a transitive dependency and hopefully the intermediate crates will have an update soon. I'm also guessing that is why we don't have a dependabot PR for this yet.

(It's certainly true that just updating Cargo.lock isn't the right thing, and I believe Cargo will end up reverting that at some point)

**Comment by bendk** [comment]
I'm not sure if this is the proper way to update sub-dependencies, but this changeset came from `cargo update -p openssl-src`.  I'm way to scared to update Cargo.lock manually.

**Comment by mhammond** [comment]
huh. I did know this but I forgot it. openssl-sys specifies openssl-src as version "111.0.1" - the thing that I forgot is that this is the same as specifying "^111.0.1" which means anything >= "111.0.1" but < "112".

So I think this is good - we should probably update all openssl related packages, but best I can tell, that's not a requirement here.

**Review by mhammond — APPROVED** [review]

**Pull request merged**
