### PR TITLE
Add new commands to nimbus-cli

### PR DESCRIPTION
**Pull request by jhugman**
Fixes [EXP-3429](https://mozilla-hub.atlassian.net/browse/EXP-3429).

### Pull Request checklist ###

- [x] **Quality**: This PR builds and tests run cleanly
  - Note:
    - For changes that need extra cross-platform testing, consider adding `[ci full]` to the PR title.
    - If this pull request includes a breaking change, consider [cutting a new release](https://github.com/mozilla/application-services/blob/main/docs/howtos/cut-a-new-release.md) after merging.
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes a changelog entry in [CHANGES_UNRELEASED.md](../CHANGES_UNRELEASED.md) or an explanation of why it does not need one
  - Any breaking changes to Swift or Kotlin binding APIs are noted explicitly
- [ ] **Dependencies**: This PR follows our [dependency management guidelines](https://github.com/mozilla/application-services/blob/main/docs/dependency-management.md)
  - Any new dependencies are accompanied by a summary of the due dilligence applied in selecting them.

[Branch builds](https://github.com/mozilla/application-services/blob/main/docs/howtos/branch-builds.md): add `[firefox-android: branch-name]` to the PR title.

### CODE REVIEW

**Comment by jhugman** [comment]
FWIW: the [same patches for Firefox for Android and iOS from #5494 ](https://github.com/mozilla/application-services/pull/5494#issuecomment-1521995106) should be applied to test these changes here.

**Comment by jeddai** [comment]
I haven't built new versions to my devices since testing #5494, thankfully!

**Review by jeddai — COMMENTED** [review]
r~wc

Functionally this works well! I went through the code as well and don't really have any changes to request there.

One thing I would like to discuss though is it seems a tad inconsistent whether a file is specified by `--file` or as a command argument. As an example, the filename is the only command argument on `capture-logs`, but `apply-file` has no command arguments and uses the `--file` flag syntax instead.

Not sure that I have a preference between the two, but I do think we should aim for it to be consistent. Perhaps when there is no other command argument the filename can be the sole command argument? Otherwise it uses the flag syntax?

**Review by jeddai — APPROVED** [review]
Looking great!! :shipit:

**Pull request closed without merging**
