### PR TITLE
Initial commit of nimbus-cli

### PR DESCRIPTION
**Pull request by jhugman**
Fixes [EXP-3425](https://mozilla-hub.atlassian.net/browse/EXP-3425).

### Pull Request checklist ###

- [x] **Quality**: This PR builds and tests run cleanly
  - Note:
    - For changes that need extra cross-platform testing, consider adding `[ci full]` to the PR title.
    - If this pull request includes a breaking change, consider [cutting a new release](https://github.com/mozilla/application-services/blob/main/docs/howtos/cut-a-new-release.md) after merging.
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes a changelog entry in [CHANGES_UNRELEASED.md](../CHANGES_UNRELEASED.md) or an explanation of why it does not need one
  - Any breaking changes to Swift or Kotlin binding APIs are noted explicitly
- [x] **Dependencies**: This PR follows our [dependency management guidelines](https://github.com/mozilla/application-services/blob/main/docs/dependency-management.md)
  - Any new dependencies are accompanied by a summary of the due dilligence applied in selecting them.

[Branch builds](https://github.com/mozilla/application-services/blob/main/docs/howtos/branch-builds.md): add `[firefox-android: branch-name]` to the PR title.

### CODE REVIEW

**Comment by jhugman** [comment]
Testing with these patches to firefox-android and firefox-ios.
[firefox-ios-cli-receiver.patch](https://github.com/mozilla/application-services/files/11297177/firefox-ios-cli-receiver.patch)
[fenix-cli-receiver.patch](https://github.com/mozilla/application-services/files/11297217/fenix-cli-receiver.patch)

**Review by tarikeshaq — CHANGES_REQUESTED** [review]
Reviewed the changes to the dependency check and the toml files! Please feel free to request a re-review whenever!

**Review by tarikeshaq — APPROVED** [review]
Removing my request for changes - thanks @jhugman!!! 🎉

**Review by tarikeshaq — COMMENTED** [review]
Just wanted to be explicit that I didn't review the remaining the PR beyond the dependency check and cargo toml leaving the business logic, etc to @jeddai

**Comment by jeddai** [comment]
Okay so with the latest code I was able to test Android and it works super well! With the ios patch I haven't been able to get it to build, I think there's an issue with the scoping on the `unwrap` function in `NimbusBuilder` maybe? Or is there a new patch I should test with?

**Comment by jhugman** [comment]
Updated patches for:

* Firefox for iOS – [firefox-ios-cli-receiver-2.patch](https://github.com/mozilla/application-services/files/11324006/firefox-ios-cli-receiver-2.patch)
* Firefox for Android — [fenix-cli-receiver-2.patch](https://github.com/mozilla/application-services/files/11324018/fenix-cli-receiver-2.patch)

I am seeing enrollments of experiments in iOS, but I think this is down to a) the fetch not being disabled, b) the database not being reset on enroll. Neither of these are part of this PR.

**Review by jeddai — APPROVED** [review]
I tested Fenix and Firefox iOS and they both worked fantastically with the CLI. This is huge, major props! 🥇

**Pull request merged**
