### PR TITLE
Add verify-ios-environment.sh script

### LINKED ISSUE #2715: Make a bootstrap script for iOS build environment
On the topic of local iOS development, our fine docs say ["we should really do a bootstrap script just like Android and Desktop"](https://github.com/mozilla/application-services/blob/master/docs/building.md#ios-development). So yeah, let's do one.

The goal here is for a developer workong on iOS code to be able to do `./libs/verify-ios-environment.sh` and see either a message that they're all set to start hacking on iOS stuff in our repo, or helpful advice on how to become so. We'll also need to update `./docs/building.md` to document it.

I'm proposing this for the "integration testing for a-s" epic because being able to easily and reliably make local builds is an important part of any integration testing.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-874)
┆Story Points: 3
┆Epic: Integration testing for a-s
┆Sprint: SYNC - end 2020-03-13

### PR DESCRIPTION
**Pull request by eoger**
Fixes #2715

### CODE REVIEW

**Comment by eoger** [comment]
> Should we have a `verify-environment.sh` script that does both (possibly only doing the ios environment if `uname` indicates we're on macOS?)

That's a great idea, I'd like to have that once we don't have to `source` the desktop one and it becomes `verify-desktop-environment.sh`.

**Comment by rfk** [comment]
Great! I'm going to try using this to guide me in getting my iOS dev environment back up to speed, as it seems to have decayed over time.

**Comment by rfk** [comment]
Running this locally, it fails with:

```
Could not find any available simulators for iOS
```

But I didn't see any tips in our docs for how to install correct simulators. I'll see if I can muddle through, but it might be useful to include some tips in the failure case here to help point new users in the right direction.

**Comment by rfk** [comment]
> Could not find any available simulators for iOS

Turns out I just had to launch XCode so it could finish installing a bunch of stuff, and this error seems to now be resolved.

**Pull request merged**
