### PR TITLE
Switch from JCenter to MavenCentral [ci full]

### PR DESCRIPTION
**Pull request by cketti**
JCenter has been sunset. See <https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/>.

### Pull Request checklist ###
- **Breaking changes**:  This PR follows our [breaking change policy](https://github.com/mozilla/application-services/blob/main/docs/howtos/breaking-changes.md)
  - [x] This PR follows the breaking change policy:
     - This PR has no breaking API changes
- [x] **Quality**: This PR builds and tests run cleanly
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
     - This PR doesn't change any code.
- [x] **Changelog**: This PR includes a changelog entry in [CHANGELOG.md](../CHANGELOG.md) or an explanation of why it does not need one
     - I don't think this change is interesting to library users. But I'd be happy to add a changelog entry in case someone disagrees.
- [x] **Dependencies**: This PR follows our [dependency management guidelines](https://github.com/mozilla/application-services/blob/main/docs/dependency-management.md)

Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866339

### CODE REVIEW

**Comment by mhammond** [comment]
I'm a little clueless about this, but is it possible to just *remove* jcenter rather than replacing it with MavenCentral?

**Comment by cketti** [comment]
The one in `/build.gradle` is required, otherwise we end up with:
```text
A problem occurred evaluating project ':autofill'.
> Could not resolve all files for configuration ':autofill:jnaForTestCopy'.
   > Could not find net.java.dev.jna:jna:5.14.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/net/java/dev/jna/jna/5.14.0/jna-5.14.0.pom
     Required by:
         project :autofill
```

The one in `/settings.gradle` is required, otherwise we end up with:
```text
Could not resolve all artifacts for configuration 'classpath'.
> Cannot resolve external dependency org.yaml:snakeyaml:2.2 because no repositories are defined.
  Required by:
      unspecified:unspecified:unspecified
```

The one in `/tools/nimbus-gradle-plugin/settings.gradle` is required, otherwise we end up with::
```text
Could not resolve all artifacts for configuration 'classpath'.
> Cannot resolve external dependency org.yaml:snakeyaml:2.2 because no repositories are defined.
  Required by:
      unspecified:unspecified:unspecified
```

The one in `/tools/nimbus-gradle-plugin/build.gradle` might not be necessary. But I don't know enough about the project to be confident in that assessment.

**Comment by cketti** [comment]
In general I'd say switching from JCenter to Maven Central is a strict improvement. Maybe one of the Android folks can confirm?

**Comment by mhammond** [comment]
I agree that switch is an improvement, but what @jonalmeida and I are trying to better understand is how moz-central uses the same dependency but apparently avoids depending on MavenCentral - if we can work that out it would be an even larger improvement :) @jonalmeida has a theory that it's built in to later gradle versions, but struggling to understand how that actually works. @rvandermeulen, do you happen to know?

**Comment by rvandermeulen** [comment]
m-c has the whole gradle-dependencies thing where it creates a local cache of everything used by Android builds so it doesn't have to touch mavenCentral directly later.

**Comment by rvandermeulen** [comment]
See also: https://searchfox.org/mozilla-central/source/taskcluster/scripts/misc/android-gradle-dependencies/nexus.xml

**Comment by rvandermeulen** [comment]
I don't see any reason not to

**Review by mhammond — APPROVED** [review]

**Pull request merged**
