### PR TITLE
Use numeric versions instead of semver for schema versions

### LINKED ISSUE #2319: Remerge: Use numeric versions instead of semver
Lina and I both agreed that this is complexity for little gain, and we should take it out, at least for now. This depends on #2066 landing, but that should happen after it comes out green in CI.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-477)
┆Story Points: 3
┆Epic: Remerge production readiness
┆Sprint: SYNC - end 2020-03-13

### PR DESCRIPTION
**Pull request by glasserc**
Fixes #2319.

### Pull Request checklist ###

- [ ] **Quality**: This PR builds and tests run cleanly
  - [x] `cargo test --all` produces no test failures
  - [ ] `cargo clippy --all --all-targets --all-features` runs without emitting any warnings
    - A bunch of warnings show up, possibly because of a new version of Rust, or because this is an old branch
  - [ ] `cargo fmt` does not produce any changes to the code
    - `cargo fmt` wants to change other components (places and sync15)
  - [ ] `./gradlew ktlint detekt` runs without emitting any warnings
    - Presumed true since I didn't touch any Kotlin code
  - [ ] `swiftformat --swiftversion 4 megazords components/*/ios && swiftlint` runs without emitting any warnings or producing changes
    - Can't verify because I don't have any Apple hardware
  - Note: For changes that need extra cross-platform testing, consider adding `[ci full]` to the PR title.
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
  - Underlying code is untested as yet
- [ ] **Changelog**: This PR includes a changelog entry in [CHANGES_UNRELEASED.md](../CHANGES_UNRELEASED.md) or an explanation of why it does not need one
  - I assume this will be covered by the same changelog entry introducing Remerge
- [x] **Dependencies**: This PR follows our [dependency management guidelines](https://github.com/mozilla/application-services/blob/master/docs/dependency-management.md)
  - No new dependencies are introduced.

### CODE REVIEW

**Comment by glasserc** [comment]
Ah, tests got added in the meantime, I need to update them..

**Comment by glasserc** [comment]
```
thread 'test_validation' panicked at 'Schema number 1 should fail to validate with an error like "VersionParseFailed", but instead failed with "FormatError(Error(\"invalid type: string \\\"garbage\\\", expected usize\", line: 1, column: 34))"', components/remerge/tests/validation.rs:31:21
```

Hmm.. should I just delete this test?

**Comment by glasserc** [comment]
I've tried to update the SQLite schema. I'm not 100% sure it's correct; I didn't see any tests for this code, and when I tried to write one, I wasn't able to make anything fail. (It seems SQLite is willing to accept strings that represent integers or vice versa.)

**Comment by thomcc** [comment]
Closing this after discussion with @glasserc -- semver versions turned out to be too valuable for syncing.

**Pull request closed without merging**
