### PR TITLE
Merge back v82.3.0 into main

### PR DESCRIPTION
**Pull request by tarikeshaq**
Merge back v82.3.0 into main to wrap up the 82.3.0 release

### CODE REVIEW

**Comment by tarikeshaq** [comment]
I won't update this PR until the artifacts for the release are built (then I'll deal with the merge conflict)

**Comment by tarikeshaq** [comment]
This should be good to merge, the `queued` task is actually done on TaskCluster.

AND lucky for us there are no merge conflicts on this one!

I imagine if I `Squash and merge` it's okay? lightly concerned Since the release tag is based on a commit on the `release-v82` branch, but I imagine git is smart enough to preserve the tag? If uncertain we can just do a merge commit and keep the branch open

**Review by mhammond — APPROVED** [review]
I'm mildly surprised check-dependencies is failing as it seems resolved on main - but I can't see how this could possibly cause it.

I think we should just merge - IIRC, we previously had the repo configured to not allow merging, but that caused problems in this release process. We should probably use a consistent process each time (so I'd also welcome an update to the docs to clarify this :)

**Comment by tarikeshaq** [comment]
> I'm mildly surprised check-dependencies is failing as it seems resolved on main - but I can't see how this could possibly cause it.

I _think_ it's since the branch doesn't have the fix (as it still is based off of the 82 release)

**Comment by mhammond** [comment]
> I  _think_ it's since the branch doesn't have the fix (as it still is based off of the 82 release)

doh - yeah, that's correct.

**Pull request merged**
