### PR TITLE
Extend logins and places 'counts' telemetry and delete 'timing' telemetry

### PR DESCRIPTION
**Pull request by mhammond**
Data review will be in https://bugzilla.mozilla.org/show_bug.cgi?id=1694316. This is a WIP to see what CI thinks about things.

### CODE REVIEW

**Review by travis79 — CHANGES_REQUESTED** [review]
For permanent collections, our data-review policy requires an IC email under `notification_emails` to be responsible for the collection.  You can still list the team email for notifications along with the IC.

**Comment by mhammond** [comment]
Thanks, done!

**Review by travis79 — APPROVED** [review]

**Comment by rfk** [comment]
@mhammond with apologies, I'm going to take the liberty of making this "ready for review" and see if i can merge it, because CI seems to have started failing on the now-expired metrics. We've got the data review and things look good in the PR to me 👍

**Review by rfk — APPROVED** [review]
🎉

**Pull request merged**
