### PR TITLE
Ensure `swift-build` task runs on pushes

### PR DESCRIPTION
**Pull request by ahal**
### Pull Request checklist ###

- **Breaking changes**:  This PR follows our [breaking change policy](https://github.com/mozilla/application-services/blob/main/docs/howtos/breaking-changes.md)
  - [x] This PR follows the breaking change policy:
     - This PR has no breaking API changes, or
     - There are corresponding PRs for our consumer applications that resolve the breaking changes and have been approved
- [x] **Quality**: This PR builds and tests run cleanly
  - Note:
    - For changes that need extra cross-platform testing, consider adding `[ci full]` to the PR title.
    - If this pull request includes a breaking change, consider [cutting a new release](https://github.com/mozilla/application-services/blob/main/docs/howtos/cut-a-new-release.md) after merging.
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes a changelog entry in [CHANGELOG.md](../CHANGELOG.md) or an explanation of why it does not need one
  - Any breaking changes to Swift or Kotlin binding APIs are noted explicitly
- [x] **Dependencies**: This PR follows our [dependency management guidelines](https://github.com/mozilla/application-services/blob/main/docs/dependency-management.md)
  - Any new dependencies are accompanied by a summary of the due dilligence applied in selecting them.

[Branch builds](https://github.com/mozilla/application-services/blob/main/docs/howtos/branch-builds.md): add `[firefox-android: branch-name]` to the PR title.

### CODE REVIEW

**Comment by ahal** [comment]
This also:

1. Upgrades CI dependencies
2. Renames the task from `swift-swift-build` -> `swift-build` (which needed a small tweak to beetmover tasks)
3. A minor drive-by simplification in beetmover transforms

**Comment by ahal** [comment]
Oh right, so I think we switched to using a `fetch` task for that NSS artifact because the artifact has a very short expiry in the NSS repo.. But this patch causes the `fetch` task to re-run, so no it's failing.

I guess we'll still need to update that artifact anytime the `fetch` task reruns now. @tarikeshaq do you know what I should update the fetch task to point to? Or should I land this and we fix it in a follow-up PR?

**Review by bendk — APPROVED** [review]
Looks good to me.

The `nss-artifact` issue is known and I'm not sure what to do about it.  It seems like that task should generally be cached which would get around the expiry issue.  Some times it is and some times it isn't and I'm not sure exactly why.   Feel free to re-open https://github.com/mozilla/application-services/issues/5681 and add some knowledge there if you know what's going on.

In the meantime, let's merge this.

**Comment by ahal** [comment]
> The nss-artifact issue is known and I'm not sure what to do about it. It seems like that task should generally be cached which would get around the expiry issue.

It is cached, but this PR must have invalidated the cache. Touching certain Taskgraph-related files can invalidate `cached_tasks`

**Comment by bendk** [comment]
> It is cached, but this PR must have invalidated the cache. Touching certain Taskgraph-related files can invalidate `cached_tasks`

I figured it was something like that.  If the issue only happens when we touch the taskgraph files, we can probably live with it for a while.

**Pull request merged**
