### PR TITLE
Use incremental vacuum for places maintenance

### PR DESCRIPTION
**Pull request by bendk**
Metrics from GLAM indicate the VACUUM command is taking a long time and doesn't seem to be dropping.  After reading the docs a bit, it seems to me that VACUUM always copies the entire database which could indeed be slow for large DBs.

Switched to using an incremental vacuum.  This only tries to truncate N pages (set to 2 here) at time rather than all free pages.  But the real speed improvement comes from only trimming completely free pages, not trying to defragment pages, which is what VACUUM does and why it needs to copy the DB.

Incremental vacuum requires a PRAGMA setting.  If that setting isn't set before there is data in the DB, then we still need to do a single full VACUUM before it can be used.

I think the result of all of this should be that we will do one slow vacuum, but future vacuums should be quick.

Also added a places-utils command to run maintenance.  I used this to test that the incremental vacuum is ineed faster.

### Pull Request checklist ###

- [ ] **Quality**: This PR builds and tests run cleanly
  - Note:
    - For changes that need extra cross-platform testing, consider adding `[ci full]` to the PR title.
    - If this pull request includes a breaking change, consider [cutting a new release](https://github.com/mozilla/application-services/blob/main/docs/howtos/cut-a-new-release.md) after merging.
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes a changelog entry in [CHANGES_UNRELEASED.md](../CHANGES_UNRELEASED.md) or an explanation of why it does not need one
  - Any breaking changes to Swift or Kotlin binding APIs are noted explicitly
- [ ] **Dependencies**: This PR follows our [dependency management guidelines](https://github.com/mozilla/application-services/blob/main/docs/dependency-management.md)
  - Any new dependencies are accompanied by a summary of the due dilligence applied in selecting them.

[Branch builds](https://github.com/mozilla/application-services/blob/main/docs/howtos/branch-builds.md): add `[ff-android: firefox-android-branch-name]` and/or `[fenix: fenix-branch-name]` to the PR title.

### CODE REVIEW

**Comment by bendk** [comment]
Tested this by running maintenance on my DB using places-utils 10 times in a row.  The full vacuum version used about 650ms total, the new version was around 160ms.

**Review by mhammond — APPROVED** [review]
:+1

**Comment by bendk** [comment]
@mhammond I needed to update this one a bit because I realized some issues with the PRAGMA statement:
  - It modifies the DB, so it can't run in a read-only connection
  - Setting the value, but not running VACUUM leaves the DB in a weird state where the old value is still active until the next VACUUM (even for fresh DBs).  I don't think this would currently lead to a bug, but it seems risky to me.  So I updated the code in `prepare()` to run VACUUM immediately after the PRAGMA.  This lead to some more code to only run that on newly-created DBs, since VACUUM might be slow for existing ones.  BTW, I couldn't move this code to `init()` because that runs in a transaction, which prevents VACUUM.

**Review by tarikeshaq — APPROVED** [review]
LGTM!

**Pull request merged**
