### PR TITLE
Fix #427 - remove unsupported iOS architectures, keep iOS 11+ only

### LINKED ISSUE #427: iOS ABI: Support 2 arch instead of 4
The `arm64` arch will cover all iOS 11 and iOS 12 capable devices. I can't imagine anyone needs iOS 9/10 devices support on new projects. We also need the x86 simulator arch. 

This is what I see currently
```
$ file ./target/universal/release/libfxaclient_ffi.a
./target/universal/release/libfxaclient_ffi.a: Mach-O universal binary with 4 architectures: [arm_v7:current ar archive] [arm64]
./target/universal/release/libfxaclient_ffi.a (for architecture armv7):	current ar archive
./target/universal/release/libfxaclient_ffi.a (for architecture i386):	current ar archive
./target/universal/release/libfxaclient_ffi.a (for architecture x86_64):	current ar archive
./target/universal/release/libfxaclient_ffi.a (for architecture arm64):	current ar archive

### PR DESCRIPTION
**Pull request by garvankeeley**
Fixes #427

### CODE REVIEW

**Comment by garvankeeley** [comment]
Need to do FxAClient ios also, updating PR...

**Comment by thomcc** [comment]
We probably should document this somewhere more visible, but if you change files in libs you'll need to update https://github.com/mozilla/application-services/blob/master/build.gradle#L87 to be the output of `git rev-parse HEAD:libs`.

We also need to get it set up so the CI stuff runs for y'alls PRs (I feel like @vladikoff might know how ot do this?)

**Comment by vladikoff** [comment]
@thomcc added @garvankeeley as contrib, that might make the CI work 👍

**Comment by garvankeeley** [comment]
While fixing this I decided to file a followup PR: https://github.com/mozilla/application-services/issues/559

**Comment by garvankeeley** [comment]
Gradle SHA needs updating, will do another PR now.

**Pull request merged**
