### PR TITLE
Uniffi webext-storage component

### PR DESCRIPTION
**Pull request by lougeniaC64**
Re-merge the webext-storage uniffication changes first introduced in #5995 and backed out due to m-c vendoring issues.

### Pull Request checklist ###

- **Breaking changes**:  This PR follows our [breaking change policy](https://github.com/mozilla/application-services/blob/main/docs/howtos/breaking-changes.md)
  - [ ] This PR follows the breaking change policy:
     - This PR has no breaking API changes, or
     - There are corresponding PRs for our consumer applications that resolve the breaking changes and have been approved
- [ ] **Quality**: This PR builds and tests run cleanly
  - Note:
    - For changes that need extra cross-platform testing, consider adding `[ci full]` to the PR title.
    - If this pull request includes a breaking change, consider [cutting a new release](https://github.com/mozilla/application-services/blob/main/docs/howtos/cut-a-new-release.md) after merging.
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes a changelog entry in [CHANGELOG.md](../CHANGELOG.md) or an explanation of why it does not need one
  - Any breaking changes to Swift or Kotlin binding APIs are noted explicitly
- [ ] **Dependencies**: This PR follows our [dependency management guidelines](https://github.com/mozilla/application-services/blob/main/docs/dependency-management.md)
  - Any new dependencies are accompanied by a summary of the due dilligence applied in selecting them.

[Branch builds](https://github.com/mozilla/application-services/blob/main/docs/howtos/branch-builds.md): add `[firefox-android: branch-name]` to the PR title.

### CODE REVIEW

**Comment by lougeniaC64** [comment]
@mhammond There were three tests that failed when I pushed to [try](https://treeherder.mozilla.org/jobs?repo=try&revision=d143843a016af5c653045168c88e3a4fea4eba44), but since they're documented as failing intermittently and I didn't introduce any logic that would affect them I think it's okay. Also, no rush on this.

**Comment by lougeniaC64** [comment]
@mhammond There were three tests that failed when I pushed to [try](https://treeherder.mozilla.org/jobs?repo=try&revision=d143843a016af5c653045168c88e3a4fea4eba44), but since they're documented as failing intermittently and I didn't introduce any logic that would affect them I think it's okay.

I will push to try again with a fresh pull from m-c, post the latest vendor of A-S so no rush.

**Comment by lougeniaC64** [comment]
Pushed to try again ([here](https://treeherder.mozilla.org/jobs?repo=try&revision=07fc8d27cd51650ac248220e724f56b4303ff188)) with the last A-S vendor and created a [WIP phabricator patch](https://phabricator.services.mozilla.com/D199142#6832315). Will mark the phabricator patch ready for review once the try job passes successfully and this PR is merged.

**Comment by lougeniaC64** [comment]
@mhammond This [try run](https://treeherder.mozilla.org/jobs?repo=try&revision=710d8da6ee8b8988546374b8898aab192301ee14) looks better I think so we should be good to go

**Review by mhammond — APPROVED** [review]
This looks great, thanks! Ignore the dependency failure, that's unrelated and I'm kinda looking at it as we speak.

**Comment by lougeniaC64** [comment]
> This looks great, thanks! Ignore the dependency failure, that's unrelated and I'm kinda looking at it as we speak.

Yeah, I was going to ask you tomorrow if we should create tickets for that and/or discuss at the meeting tomorrow but sounds good.

**Pull request merged**
