### PR TITLE
Update Glean to v53.2.0

### PR DESCRIPTION
**Pull request by rvandermeulen**

### CODE REVIEW

**Comment by rvandermeulen** [comment]
The swiftlint and check-protobuf-uptodate failures look unrelated to this patch.

**Comment by rvandermeulen** [comment]
Fixed the protobuf failures now. Just the unrelated swiftlint failures now (which I filed an issue for).

**Review by travis79 — APPROVED** [review]
Looks good to me, I can't recall if there are any references to the specific glean parser versions in A-S but I think there was an update to Glean Parser that went along with this Glean release.

**Comment by rvandermeulen** [comment]
Yeah, I didn't see any either when I looked.

**Pull request merged**
