### PR TITLE
Update UniFFi to 0.26

### PR DESCRIPTION
**Pull request by skhamis**
Should fix failures in CI as well.

What likely happened is cargo will still take the patch bump still even if `weedle = 4.0.0`. However there doesn't seem like any blockers to just bumping to 0.26.

### Pull Request checklist ###

- **Breaking changes**:  This PR follows our [breaking change policy](https://github.com/mozilla/application-services/blob/main/docs/howtos/breaking-changes.md)
  - [ ] This PR follows the breaking change policy:
     - This PR has no breaking API changes, or
     - There are corresponding PRs for our consumer applications that resolve the breaking changes and have been approved
- [ ] **Quality**: This PR builds and tests run cleanly
  - Note:
    - For changes that need extra cross-platform testing, consider adding `[ci full]` to the PR title.
    - If this pull request includes a breaking change, consider [cutting a new release](https://github.com/mozilla/application-services/blob/main/docs/howtos/cut-a-new-release.md) after merging.
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes a changelog entry in [CHANGELOG.md](../CHANGELOG.md) or an explanation of why it does not need one
  - Any breaking changes to Swift or Kotlin binding APIs are noted explicitly
- [ ] **Dependencies**: This PR follows our [dependency management guidelines](https://github.com/mozilla/application-services/blob/main/docs/dependency-management.md)
  - Any new dependencies are accompanied by a summary of the due dilligence applied in selecting them.

[Branch builds](https://github.com/mozilla/application-services/blob/main/docs/howtos/branch-builds.md): add `[firefox-android: branch-name]` to the PR title.

### CODE REVIEW

**Comment by mhammond** [comment]
Thanks Sammy, but I don't think we should take this yet, but instead use Ben's new 0.25.4

**Comment by bendk** [comment]
> Thanks Sammy, but I don't think we should take this yet, but instead use Ben's new 0.25.4

Do you mean 0.26.1?  I just released that one.  I'm not planning on doing a `0.25.x` release, yanking `weedle2 4.0.1`  should fix that.

**Comment by mhammond** [comment]
Oh right. So yeah, in that case no action needs to be taken, right (although individuals my need to `cargo update weedle2`) - right?

**Comment by bendk** [comment]
> Oh right. So yeah, in that case no action needs to be taken, right (although individuals my need to `cargo update weedle2`) - right?

Correct and I doubt individuals will need to do that.  It would only be required if you personally ran `cargo update` before and checked in the new `Cargo.lock` file.

**Comment by skhamis** [comment]
Gonna go ahead and close this, idk why I hit the deps issue but feel free to take it whenever the coordination with Glean happens!

**Pull request closed without merging**
