### PR TITLE
Use openid-config for OAuth, profile URLs

### LINKED ISSUE #47: Use "openid-configuration" for OAuth discovery
Instead of a list of servers from fxa-client-configuration

https://github.com/mozilla/application-services/blob/28d5f7277414459e736ee68cfaf02214a211a3cd/fxa-rust-client/src/config.rs#L31

we need to use https://accounts.firefox.com/.well-known/openid-configuration to discovery oauth endpoints.

Especially important for https://github.com/mozilla/fxa-content-server/issues/6113

cc @rfk

### PR DESCRIPTION
**Pull request by carolkng**
@vladikoff @eoger: -r?
fixes #47

### CODE REVIEW

**Comment by vladikoff** [comment]
@carolkng side note, try to fix your GitHub configuration, your commits are not associated with your account properly:

image

**Comment by eoger** [comment]
LGTM, @vladikoff did your test worked?

**Comment by vladikoff** [comment]
> LGTM, @vladikoff did your test work? 

Going to try again today...

**Comment by vladikoff** [comment]
Awesome work @carolkng , tested and works well 👍

**Pull request merged**
