### PR TITLE
ci: Use standard Taskgraph cache routes

### PR DESCRIPTION
**Pull request by ahal**
### Pull Request checklist ###

- [x] **Quality**: This PR builds and tests run cleanly
  - Note:
    - For changes that need extra cross-platform testing, consider adding `[ci full]` to the PR title.
    - If this pull request includes a breaking change, consider [cutting a new release](https://github.com/mozilla/application-services/blob/main/docs/howtos/cut-a-new-release.md) after merging.
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes a changelog entry in [CHANGES_UNRELEASED.md](../CHANGES_UNRELEASED.md) or an explanation of why it does not need one
  - Any breaking changes to Swift or Kotlin binding APIs are noted explicitly
- [x] **Dependencies**: This PR follows our [dependency management guidelines](https://github.com/mozilla/application-services/blob/main/docs/dependency-management.md)
  - Any new dependencies are accompanied by a summary of the due dilligence applied in selecting them.

[Branch builds](https://github.com/mozilla/application-services/blob/main/docs/howtos/branch-builds.md): add `[firefox-android: branch-name]` to the PR title.

### CODE REVIEW

**Comment by tarikeshaq** [comment]
ios Circle CI failure is unrelated, so I re-ran it, I'll file a ticket for a flakey test

**Review by hneiva — APPROVED** [review]
Rubber-stamp'd

**Comment by ahal** [comment]
@tarikeshaq could you help get this merged? I appear to be in a constant state of being unable to merge due to needing to rebase onto latest main, but then having the previous review discarded :p

**Comment by tarikeshaq** [comment]
Aaah thanks @ahal I got it from here, apologies for the merge dance - Looks like the filing job is failing on a 404, I'm assuming that's intermittent? (usually I'd assume so on a 404, but we're changing routes so 😅)

**Comment by ahal** [comment]
> Aaah thanks @ahal I got it from here, apologies for the merge dance - Looks like the filing job is failing on a 404, I'm assuming that's intermittent? (usually I'd assume so on a 404, but we're changing routes so 😅)

Hm, yeah that doesn't look familiar to me, and this PR had a green CI run prior to me rebasing. So I'd guess it's intermittent? Looks like it's trying to reference an artifact that expired.

**Comment by tarikeshaq** [comment]
Yeah confirmed that the issue is unrelated, looks like the NSS artifact for macos is giving back a 404, filing a separate ticket for that

**Pull request merged**
