### PR TITLE
Publish nimbus cli

### PR DESCRIPTION
**Pull request by bendk**
Publish nimbus-cli
    
  - Split up the `nimbus-cli` assemble task from `nimbus-fml`
  - Leverage the transform more for this, which helps avoid duplicating code between the two tasks
  - Publish `nimbus-cli` at a separate index with each binary as a separate artifact.

### Pull Request checklist ###

- [ ] **Quality**: This PR builds and tests run cleanly
  - Note:
    - For changes that need extra cross-platform testing, consider adding `[ci full]` to the PR title.
    - If this pull request includes a breaking change, consider [cutting a new release](https://github.com/mozilla/application-services/blob/main/docs/howtos/cut-a-new-release.md) after merging.
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes a changelog entry in [CHANGELOG.md](../CHANGELOG.md) or an explanation of why it does not need one
  - Any breaking changes to Swift or Kotlin binding APIs are noted explicitly
- [ ] **Dependencies**: This PR follows our [dependency management guidelines](https://github.com/mozilla/application-services/blob/main/docs/dependency-management.md)
  - Any new dependencies are accompanied by a summary of the due dilligence applied in selecting them.

[Branch builds](https://github.com/mozilla/application-services/blob/main/docs/howtos/branch-builds.md): add `[firefox-android: branch-name]` to the PR title.

### CODE REVIEW

**Comment by bendk** [comment]
I believe I got the taskcluster code working, does it look okay to you @ahal?

One of the last questions is exactly how to package up `nimbus-cli`.  My first pass:
  - Created separate artifacts for each target
  - Zipped up the binaries
  - Used the same structure as nimbus-fml (the actual binary is in `{target}/release/nimbus-cli`)

What do you think of that @jhugman?  I'm happy to change the packaging to whatever works best for the consumers.

**Comment by bendk** [comment]
You can find nimbus-cli artifacts in this task: https://firefox-ci-tc.services.mozilla.com/tasks/aj0i0jbtSxSLN465k7lRtg

Once this is merged, these will also be in an index for easy retrieval by scripts or whatever.

**Comment by jhugman** [comment]
> I believe I got the taskcluster code working, does it look okay to you @ahal?
> 
> One of the last questions is exactly how to package up `nimbus-cli`. My first pass:
> 
>     * Created separate artifacts for each target 
>     * Zipped up the binaries
>     * Used the same structure as nimbus-fml (the actual binary is in `{target}/release/nimbus-cli`)
> 
> What do you think of that @jhugman? I'm happy to change the packaging to whatever works best for the consumers.

This looks just fine to me!

**Review by ahal — APPROVED** [review]
This looks great!

**Review by jhugman — APPROVED** [review]
Looks great!

**Pull request merged**
