### PR TITLE
[DISCO-2661] Suggest: fix: use lowercase keyword to find suggestion

### PR DESCRIPTION
**Pull request by tiftran**
### Pull Request checklist ###

- **Breaking changes**:  This PR follows our [breaking change policy](https://github.com/mozilla/application-services/blob/main/docs/howtos/breaking-changes.md)
  - [ ] This PR follows the breaking change policy:
     - This PR has no breaking API changes, or
     - There are corresponding PRs for our consumer applications that resolve the breaking changes and have been approved
- [ ] **Quality**: This PR builds and tests run cleanly
  - Note:
    - For changes that need extra cross-platform testing, consider adding `[ci full]` to the PR title.
    - If this pull request includes a breaking change, consider [cutting a new release](https://github.com/mozilla/application-services/blob/main/docs/howtos/cut-a-new-release.md) after merging.
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes a changelog entry in [CHANGELOG.md](../CHANGELOG.md) or an explanation of why it does not need one
  - Any breaking changes to Swift or Kotlin binding APIs are noted explicitly
- [ ] **Dependencies**: This PR follows our [dependency management guidelines](https://github.com/mozilla/application-services/blob/main/docs/dependency-management.md)
  - Any new dependencies are accompanied by a summary of the due dilligence applied in selecting them.

[Branch builds](https://github.com/mozilla/application-services/blob/main/docs/howtos/branch-builds.md): add `[firefox-android: branch-name]` to the PR title.

### CODE REVIEW

**Comment by linabutler** [comment]
This looks great, thanks!

I have a suggestion for another way to do this, that might be interesting to think about, and if you're curious 😊 Columns in SQLite can have ["collation sequences"](https://www.sqlite.org/datatype3.html#collation) that define how to compare strings in that column.

As an alternative to lowercasing the keywords at query time, we can declare the `NOCASE` collation on the columns we want, like this:

```sql
CREATE TABLE keywords(
        keyword TEXT NOT NULL COLLATE NOCASE,
        ...
);

CREATE TABLE prefix_keywords(
        keyword_prefix TEXT NOT NULL COLLATE NOCASE,
        keyword_suffix TEXT NOT NULL DEFAULT '' COLLATE NOCASE,
        ...
);
```

And then SQLite will store and query those keywords in a case-insensitive way. I like it for two reasons: it's not possible to accidentally forget to normalize the string at query or storage time, and it lets you define language-specific collations.

`COLLATE NOCASE`'s biggest drawback is that it doesn't do case-folding for non-ASCII characters—which isn't a problem for Suggest now, but good to keep in mind for when we expand. Rust's `to_lowercase()` is more Unicode-aware than `COLLATE NOCASE`, but still not suitable for general case-insensitive comparisons, because those rules can be language-specific. In German, `SS` and `ß` are equivalent ignoring case; meanwhile, in Turkish, `I` and `i` are two different letters that are not equivalent. It turns out [there are a lot of rules that go into a case-insensitive string comparison](https://unicode-org.github.io/icu/userguide/collation/)!

Luckily, though, we don't have to worry about any of those for a while!

**Review by linabutler — APPROVED** [review]

**Comment by tiftran** [comment]
> This looks great, thanks!
> 
> I have a suggestion for another way to do this, that might be interesting to think about, and if you're curious 😊 Columns in SQLite can have ["collation sequences"](https://www.sqlite.org/datatype3.html#collation) that define how to compare strings in that column.
> 
> As an alternative to lowercasing the keywords at query time, we can declare the `NOCASE` collation on the columns we want, like this:
> 
> ```sql
> CREATE TABLE keywords(
>         keyword TEXT NOT NULL COLLATE NOCASE,
>         ...
> );
> 
> CREATE TABLE prefix_keywords(
>         keyword_prefix TEXT NOT NULL COLLATE NOCASE,
>         keyword_suffix TEXT NOT NULL DEFAULT '' COLLATE NOCASE,
>         ...
> );
> ```
> 
> And then SQLite will store and query those keywords in a case-insensitive way. I like it for two reasons: it's not possible to accidentally forget to normalize the string at query or storage time, and it lets you define language-specific collations.
> 
> `COLLATE NOCASE`'s biggest drawback is that it doesn't do case-folding for non-ASCII characters—which isn't a problem for Suggest now, but good to keep in mind for when we expand. Rust's `to_lowercase()` is more Unicode-aware than `COLLATE NOCASE`, but still not suitable for general case-insensitive comparisons, because those rules can be language-specific. In German, `SS` and `ß` are equivalent ignoring case; meanwhile, in Turkish, `I` and `i` are two different letters that are not equivalent. It turns out [there are a lot of rules that go into a case-insensitive string comparison](https://unicode-org.github.io/icu/userguide/collation/)!
> 
> Luckily, though, we don't have to worry about any of those for a while!

Would it be overkill to have both?

**Comment by linabutler** [comment]
> Would it be overkill to have both?

Yeah, I feel like it would be overkill to have both—one or the other would be good 😅 The way you have it now is great to land!

**Comment by tiftran** [comment]
@mergifyio backport release-v120

**Pull request merged**
