### PR TITLE
Add metrics for fetch and apply experiments

### PR DESCRIPTION
**Pull request by jhugman**
Fixes [EXP-3083](https://mozilla-hub.atlassian.net/browse/EXP-3083).

### Pull Request checklist ###

- [ ] **Quality**: This PR builds and tests run cleanly
  - Note:
    - For changes that need extra cross-platform testing, consider adding `[ci full]` to the PR title.
    - If this pull request includes a breaking change, consider [cutting a new release](https://github.com/mozilla/application-services/blob/main/docs/howtos/cut-a-new-release.md) after merging.
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes a changelog entry in [CHANGES_UNRELEASED.md](../CHANGES_UNRELEASED.md) or an explanation of why it does not need one
  - Any breaking changes to Swift or Kotlin binding APIs are noted explicitly
- [ ] **Dependencies**: This PR follows our [dependency management guidelines](https://github.com/mozilla/application-services/blob/main/docs/dependency-management.md)
  - Any new dependencies are accompanied by a summary of the due dilligence applied in selecting them.

[Branch builds](https://github.com/mozilla/application-services/blob/main/docs/howtos/branch-builds.md): add `[ff-android: firefox-android-branch-name]` and/or `[fenix: fenix-branch-name]` to the PR title.

### CODE REVIEW

**Comment by jhugman** [comment]
# Request for data collection review form

1) What questions will you answer with this data?

How long does a fetch take, which requires a network connection?
How long does the enrollment calculation take?

2) Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements? Some example responses:

These metrics are important for monitoring of Nimbus experiments, to ensure proper experiment execution, especially for early in launch experiments and first run experiments.

The enrollment calculation is important as it is possible that the application blocks the main thread (the UI thread) while waiting for this, and on slow devices— we believe—
this disk access is slow enough to cause the user to receive Application Not Responding warnings. Measuring this here is a way of deciding if we should block the main thread or not.

Knowing the fetch time is a good guide for app developers to make the decision as to whether to bundle the first run experiment or to download them on first launch.

Additionally, both metrics are key health indicators of the Nimbus SDK and surrounding system.

3) What alternative methods did you consider to answer these questions? Why were they not sufficient?

No existing telemetry or error provides this information.

4) Can current instrumentation answer these questions?

No.

5) List all proposed measurements and indicate the category of data collection for each measurement, using the [Firefox data collection categories](https://wiki.mozilla.org/Data_Collection) found on the Mozilla wiki.

**Note that the data steward reviewing your request will characterize your data collection based on the highest (and most sensitive) category.**

<table>
  <tr>
    <td>Measurement Description</td>
    <td>Data Collection Category</td>
    <td>Tracking Bug #</td>
  </tr>
  <tr>
    <td>apply_pending_experiments_time timing distribution</td>
    <td>Category 1 - Technical Data</td>
    <td>[Jira EXP-3083](https://mozilla-hub.atlassian.net/browse/EXP-3083)</td>
  </tr>
  <tr>
    <td>fetch_experiments_time timing distribution</td>
    <td>Category 1 - Technical Data</td>
    <td>[Jira EXP-3083](https://mozilla-hub.atlassian.net/browse/EXP-3083)</td>
  </tr>
</table>

6) Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way.

This collection is documented in the [Glean Dictionary](https://dictionary.telemetry.mozilla.org/) and in the metrics.yaml in /components/nimbus

7) How long will this data be collected?  Choose one of the following:

We want to permanently monitor this data - Nimbus Team (nimbus-dev@mozilla.com)

8) What populations will you measure?

All channels, countries, and locales

9) If this data collection is default on, what is the opt-out mechanism for users?

Through the standard telemetry preference in the application settings

10) Please provide a general description of how you will analyze this data.

Through Looker and Redash.

11) Where do you intend to share the results of your analysis?

With experiment team members and mobile application developers.

12)  Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection?

No.

**Comment by eliserichards** [comment]
> # Request for data collection review form
> 
>     1. What questions will you answer with this data?
> 
> 
> How long does a fetch take, which requires a network connection? How long does the enrollment calculation take?
> 
>     2. Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements? Some example responses:
> 
> 
> These metrics are important for monitoring of Nimbus experiments, to ensure proper experiment execution, especially for early in launch experiments and first run experiments.
> 
> The enrollment calculation is important as it is possible that the application blocks the main thread (the UI thread) while waiting for this, and on slow devices— we believe— this disk access is slow enough to cause the user to receive Application Not Responding warnings. Measuring this here is a way of deciding if we should block the main thread or not.
> 
> Knowing the fetch time is a good guide for app developers to make the decision as to whether to bundle the first run experiment or to download them on first launch.
> 
> Additionally, both metrics are key health indicators of the Nimbus SDK and surrounding system.
> 
>     3. What alternative methods did you consider to answer these questions? Why were they not sufficient?
> 
> 
> No existing telemetry or error provides this information.
> 
>     4. Can current instrumentation answer these questions?
> 
> 
> No.
> 
>     5. List all proposed measurements and indicate the category of data collection for each measurement, using the [Firefox data collection categories](https://wiki.mozilla.org/Data_Collection) found on the Mozilla wiki.
> 
> 
> **Note that the data steward reviewing your request will characterize your data collection based on the highest (and most sensitive) category.**
> Measurement Description 	Data Collection Category 	Tracking Bug #
> `apply_pending_experiments_time` timing distribution 	Category 1 - Technical Data 	[Jira EXP-3083](https://mozilla-hub.atlassian.net/browse/EXP-3083)
> `fetch_experiments_time timing` distribution 	Category 1 - Technical Data 	[Jira EXP-3083](https://mozilla-hub.atlassian.net/browse/EXP-3083)
> 
>     6. Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way.
> 
> 
> This collection is documented in the [Glean Dictionary](https://dictionary.telemetry.mozilla.org/) and in the metrics.yaml in /components/nimbus
> 
>     7. How long will this data be collected?  Choose one of the following:
> 
> 
> We want to permanently monitor this data - Nimbus Team ([nimbus-dev@mozilla.com](mailto:nimbus-dev@mozilla.com))
> 
>     8. What populations will you measure?
> 
> 
> All channels, countries, and locales
> 
>     9. If this data collection is default on, what is the opt-out mechanism for users?
> 
> 
> Through the standard telemetry preference in the application settings
> 
>     10. Please provide a general description of how you will analyze this data.
> 
> 
> Through Looker and Redash.
> 
>     11. Where do you intend to share the results of your analysis?
> 
> 
> With experiment team members and mobile application developers.
> 
>     12. Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection?
> 
> 
> No.

# Data Review Form (to be filled by Data Stewards)

1) Is there or will there be **documentation** that describes the schema for the ultimate data set in a public, complete, and accurate way? 

    * Yes, through the `metrics.yaml` file in `/components/nimbus`, and the [Glean Dictionary](https://dictionary.telemetry.mozilla.org/).

2) Is there a control mechanism that allows the user to turn the data collection on and off? (Note, for data collection not needed for security purposes, Mozilla provides such a control mechanism) Provide details as to the control mechanism available.

    * Yes, through the normal opt-out mechanisms in the application settings.

3) If the request is for permanent data collection, is there someone who will monitor the data over time?

    * Yes, this will be a permanent collection with nimbus-dev@mozilla.com to monitor.

4) Using the **[category system of data types](https://wiki.mozilla.org/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?

    * Category 1 - technical data.

5) Is the data collection request for default-on or default-off?

    * Default-on.

6) Does the instrumentation include the addition of **any *new* identifiers** (whether anonymous or otherwise; e.g., username, random IDs, etc.  See the appendix for more details)?

    * No

7) Is the data collection covered by the existing Firefox privacy notice? 

    * Yes

8) Does the data collection use a third-party collection tool? **If yes, escalate to legal.**

    * No

## Result

data-review+

**Review by eliserichards — CHANGES_REQUESTED** [review]
Small nit: you should add your email as well as `nimbus-dev` since this is permanent

**Review by travis79 — APPROVED** [review]
🎉 This looks great

**Pull request merged**
