### PR TITLE
Bug 1889982 - Upload android symbols [ci full]

### PR DESCRIPTION
**Pull request by bendk**
### Pull Request checklist ###

- **Breaking changes**:  This PR follows our [breaking change policy](https://github.com/mozilla/application-services/blob/main/docs/howtos/breaking-changes.md)
  - [ ] This PR follows the breaking change policy:
     - This PR has no breaking API changes, or
     - There are corresponding PRs for our consumer applications that resolve the breaking changes and have been approved
- [ ] **Quality**: This PR builds and tests run cleanly
  - Note:
    - For changes that need extra cross-platform testing, consider adding `[ci full]` to the PR title.
    - If this pull request includes a breaking change, consider [cutting a new release](https://github.com/mozilla/application-services/blob/main/docs/howtos/cut-a-new-release.md) after merging.
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes a changelog entry in [CHANGELOG.md](../CHANGELOG.md) or an explanation of why it does not need one
  - Any breaking changes to Swift or Kotlin binding APIs are noted explicitly
- [ ] **Dependencies**: This PR follows our [dependency management guidelines](https://github.com/mozilla/application-services/blob/main/docs/dependency-management.md)
  - Any new dependencies are accompanied by a summary of the due diligence applied in selecting them.

[Branch builds](https://github.com/mozilla/application-services/blob/main/docs/howtos/branch-builds.md): add `[firefox-android: branch-name]` to the PR title.

### CODE REVIEW

**Comment by bendk** [comment]
This is definitely not ready for review, I need to iterate through some more CI runs first.

**Comment by mhammond** [comment]
Thanks heaps for looking at this Ben!

**Comment by bendk** [comment]
Okay, I think this one is ready for review now.

I'm not sure how the best way to test this.  I checked the symbols tarball from the `module-build-full-megazord` task and it sort-of looked okay to me, but I don't know how to really judge this.  Also, the `upload-symbols` task seems like it's working, but I don't have any more confidence than that.  I guess we could merge and test it with the next nightly?

**Review by mhammond — APPROVED** [review]
Seems fine to me, and the worst that should happen is we still don't get the symbols we expect - so seems fine to land and see what happens!

**Comment by bendk** [comment]
Sounds good to me, let's try this :crossed_fingers:

**Pull request merged**
