### PR TITLE
Store i64 in sync15::ServerTimestamp

### PR DESCRIPTION
**Pull request by lyuyuan92**
Store an i64 instead of f64 in sync15::ServerTimestamp.

Signed-off-by: YLyu <lyuyuan92@gmail.com>

Issue #815

### CODE REVIEW

**Comment by thomcc** [comment]
Sorry, you'll need to set up commit signing before we can land this, https://help.github.com/en/articles/signing-commits goes over the steps necessary to do this.

**Comment by lyuyuan92** [comment]
> Sorry, you'll need to set up commit signing before we can land this, https://help.github.com/en/articles/signing-commits goes over the steps necessary to do this.

Hi Thom, I have set up commit signing. Please let me know if there is anything missing. Thanks!

**Comment by mhammond** [comment]
Sorry @lyuyuan92, but we had to back this out because various tests were failing - running `cargo test` from the root of the repo will show you some of the failures.

There's also an issue that the `FromStr for ServerTimestamp` must still handle the fact it comes in as a float, and for symmetry, I suggest that `Display` prints in the same format (ie, as the float, not the int)

**Comment by lyuyuan92** [comment]
> Sorry @lyuyuan92, but we had to back this out because various tests were failing - running `cargo test` from the root of the repo will show you some of the failures.
> 
> There's also an issue that the `FromStr for ServerTimestamp` must still handle the fact it comes in as a float, and for symmetry, I suggest that `Display` prints in the same format (ie, as the float, not the int)

Oh sorry! I have run all test before rebase but forgot to do it again after. Could you reopen this PR so that I can update my forked branch? Or you would like me to create a new PR instead?

**Comment by thomcc** [comment]
Github doesn't seem to give us an option to reopen this, but if you submit a new one, that would be fine.

**Pull request merged**
