### PR TITLE
Fixes nightly fml taskcluster job

### PR DESCRIPTION
**Pull request by tarikeshaq**
Testing if the job will work, will mark as ready for review when ready

### CODE REVIEW

**Comment by jhugman** [comment]
@tarikeshaq I've just seen this, and added an `--install-only` flag to the work I've been doing in https://github.com/mozilla/application-services/pull/5532. Let me know if there's anything else you'd like doing.

**Comment by tarikeshaq** [comment]
Thanks @jhugman! I'm working through this, I filed https://mozilla-hub.atlassian.net/browse/SYNC-3706 as it wasn't as easy as I had hoped it would be, but I have a few ideas to try out 🤞

**Comment by bendk** [comment]
Should we close this?  I'm pretty close to getting this working in https://github.com/mozilla/application-services/pull/5543.

**Comment by tarikeshaq** [comment]
Yes! Thanks, Ben, closing

**Pull request closed without merging**
