### PR TITLE
Adds error-support to the iOS megazords

### PR DESCRIPTION
**Pull request by tarikeshaq**
fixes https://mozilla-hub.atlassian.net/browse/SYNC-3263

This is blocked on https://github.com/mozilla/uniffi-rs/pull/1310 
### Pull Request checklist ###

- [x] **Quality**: This PR builds and tests run cleanly
  - Note:
    - For changes that need extra cross-platform testing, consider adding `[ci full]` to the PR title.
    - If this pull request includes a breaking change, consider [cutting a new release](https://github.com/mozilla/application-services/blob/main/docs/howtos/cut-a-new-release.md) after merging.
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes a changelog entry in [CHANGES_UNRELEASED.md](../CHANGES_UNRELEASED.md) or an explanation of why it does not need one
  - Any breaking changes to Swift or Kotlin binding APIs are noted explicitly
- [x] **Dependencies**: This PR follows our [dependency management guidelines](https://github.com/mozilla/application-services/blob/main/docs/dependency-management.md)
  - Any new dependencies are accompanied by a summary of the due dilligence applied in selecting them.

[Branch builds](https://github.com/mozilla/application-services/blob/main/docs/howtos/branch-builds.md): add `[ac: android-components-branch-name]` and/or `[fenix: fenix-branch-name]` to the PR title.

### CODE REVIEW

**Comment by bendk** [comment]
Seems fine to me, but I don't understand the iOS stuff that well. Maybe @lougeniaC64 @skhamis can review that?

**Comment by skhamis** [comment]
The error in the CI produces:

```
/Users/distiller/project/components/support/error/ios/Generated/errorsupport.swift:370:47: incorrect argument label in call (have 'type_name:message:', expected 'typeName:message:')

            swiftCallbackInterface.reportError(
```

which seems trivial to fix but this is happening in the generated code?

**Comment by tarikeshaq** [comment]
Yup!! https://github.com/mozilla/uniffi-rs/pull/1310 fixes that, we just need a UniFFI  release

**Review by skhamis — APPROVED** [review]
Exciting to have this in iOS! LGTM 🚀

**Comment by tarikeshaq** [comment]
eeeeh circle jobs are not being reported here for some reason. I see them running in https://app.circleci.com/pipelines/github/mozilla/application-services?branch=expose-error-support-ios though 😕

**Comment by tarikeshaq** [comment]
welp, removing cookies/site data and re-opening didn't help this time

**Pull request merged**
