### PR TITLE
Update Rust version to 1.75, MSR to 1.70

### PR DESCRIPTION
**Pull request by mhammond**
m-c is now on [1.75 for workers](https://bugzilla.mozilla.org/show_bug.cgi?id=1857090), [1.70 for MSR](https://searchfox.org/mozilla-central/source/python/mozboot/mozboot/util.py#14). As per [our policy](https://github.com/mozilla/application-services/blob/main/docs/design/rust-versions.md), we should update.

### CODE REVIEW

**Review by bendk — APPROVED** [review]
Looks great!  :rocket:

**Comment by bendk** [comment]
I just updated this branch purely to test if the CI would pass now.  I believe we had some updates to the mac workers, so maybe it will just work?

**Comment by bendk** [comment]
Looks like that worked.  What do you think about rebase and merging?

**Comment by mhammond** [comment]
I'm fine with that - I was waiting to see if @badboy had any concerns or wanted us to hold off, but now he is back from PTO I think we can take silence as consent :)

**Comment by badboy** [comment]
oh sorry, no blocker from my side!

**Pull request merged**
