### PR TITLE
Update nimbus-sdk to v0.7.1

### PR DESCRIPTION
**Pull request by mhammond**

### CODE REVIEW

**Comment by rfk** [comment]
I think you need to `cargo update` or similar to pull the updates into the main `Cargo.lock` file.

**Review by rfk — APPROVED** [review]
r+ because there's nothing controversial going on here, please merge whenever CI is happy

**Comment by mhammond** [comment]
> I think you need to `cargo update` or similar to pull the updates into the main `Cargo.lock` file.

Ah, thanks - `cargo update -p nimbus-sdk` seems to be what I want - without the param it updates the world

**Comment by mhammond** [comment]
*sigh* - and `-p autofill`, and update a few other references to the uniffi version

**Pull request merged**
