### PR TITLE
Build nimbus-cli on Circle CI.

### PR DESCRIPTION
**Pull request by jhugman**
Fixes [EXP-3428](https://mozilla-hub.atlassian.net/browse/EXP-3428).

### Pull Request checklist ###

- [x] **Quality**: This PR builds and tests run cleanly
  - Note:
    - For changes that need extra cross-platform testing, consider adding `[ci full]` to the PR title.
    - If this pull request includes a breaking change, consider [cutting a new release](https://github.com/mozilla/application-services/blob/main/docs/howtos/cut-a-new-release.md) after merging.
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes a changelog entry in [CHANGES_UNRELEASED.md](../CHANGES_UNRELEASED.md) or an explanation of why it does not need one
  - Any breaking changes to Swift or Kotlin binding APIs are noted explicitly
- [ ] **Dependencies**: This PR follows our [dependency management guidelines](https://github.com/mozilla/application-services/blob/main/docs/dependency-management.md)
  - Any new dependencies are accompanied by a summary of the due dilligence applied in selecting them.

[Branch builds](https://github.com/mozilla/application-services/blob/main/docs/howtos/branch-builds.md): add `[firefox-android: branch-name]` to the PR title.

### CODE REVIEW

**Review by tarikeshaq — COMMENTED** [review]
This looks great! thanks @jhugman! In terms of the story of getting this into QA's hands:

- If QA needs a new version, for now, they'll have to get it through Circle CI, for example: https://app.circleci.com/pipelines/github/mozilla/application-services/33741/workflows/158560cd-d2fe-46c9-a32f-7efa6cd68d36/jobs/160629/artifacts
- I'm assuming if a QA member already has the binary then all is good, and if they don't the process would be:
    - Find the `nimbus-artifacts-and-cli` job on the `main` branch
    - click into it until you get to Circle, and download the artifact from circle
    - Does that sound too invasive?
- The artifacts will be available on any GitHub Releases we do, and that is probably easier for QA to get, but now that we follow Firefox's cadence, we won't have many non-nightly releases. In other words, if the CLI is rapidly changing we'd probably direct QA to Circle again
- It might be possible to also release this through taskcluster, but that's currently blocked on https://mozilla-hub.atlassian.net/browse/SYNC-3706. Unless we expect the CLI to need to be aligned to the megazord (i.e have a dependency on the interface of nimbus itself) we might be okay keeping the artifacts on Circle for now


What are your thoughts @jhugman? What are your thoughts on the ideal story for QA retrieving this binary given application-services changing its release process?

**Comment by jeddai** [comment]
I'd argue for this CLI we should try and make it as easy as possible for users to a) download it, and b) keep it up to date. 

* The CLI should probably passively check on any command run to see if it's still the latest version. Not sure what it should be checking against, but I still think it should.
  * We could then follow in the footsteps of many libraries before us by writing a shell script that we can pipe to bash on a curl and it'll install/update the binary in the right local path and everything. (e.g. [helm install script](https://helm.sh/docs/intro/install/#from-script))
  `curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash`
* If we do the above then we can have super straight-forward install instructions on the [mozilla/experimenter-docs](https://github.com/mozilla/experimenter-docs) site

**Comment by jhugman** [comment]
At the moment, no one has the binary.

For now, I'm expecting QA to find some things they don't like, bugs, etc which will require small amounts of ongoing development, but long term, I'm not expecting frequent updates.

I think my ideal would be:

0. The `nimbus-cli` users to have access to a bash shell.
0. They follow instructions on https://experimenter.info to install, hopefully `curl https://raw.githubusercontent.com/mozilla/application-services/tools/get-nimbus-cli.sh | sh` (hopefully, because this won't be so clean with Windows/PowerShell in the picture)
0. Use something like [`update-informer`](https://crates.io/crates/update-informer) which periodically checks for updates.
0.  When an update is available, they're told to repeat the installation process.

So, I can see we can start a couple of users off with the Circle-CI workflow, without any of the nice installation instructions, or update-informers.

We can build in nice instructions and update flows focussing on Github releases, up until [SYNC-3706](https://mozilla-hub.atlassian.net/browse/SYNC-3706) is fixed, then switch the install script and the update informer to check there instead. 

Aternatives considered:

1. maintain a version string in the `Cargo.toml` of `nimbus-cli` and check the version on`main`, then download from taskcluster. Good: allows `nimbus-cli` to release off train. Bad: easy to get the `main` and task cluster out of sync shortly after an increment of the version.
2. use https://crates.io : Good: tooling already built, allows `nimbus-cli` to release off train. Bad: forces QA and devs to have Rust tooling.

Other thoughts:

1. Should the `nimbus-cli` take care of unpacking the zip file, and replacing itself? Sounds risky, but cuts out another step.
2. How might we choose the right place to put the `nimbus-cli` binary? This would be the job of an **installer**.
3. Should we build installers (perhaps with [`cargo bundle`](https://crates.io/crates/cargo-bundle))

**Comment by jhugman** [comment]
At the moment, no one has the binary.

For now, I'm expecting QA to find some things they don't like, bugs, etc which will require small amounts of ongoing development, but long term, I'm not expecting frequent updates.

I think my ideal would be:

0. The `nimbus-cli` users to have access to a bash shell.
0. They follow instructions on https://experimenter.info to install, hopefully `curl https://raw.githubusercontent.com/mozilla/application-services/tools/get-nimbus-cli.sh | sh` (hopefully, because this won't be so clean with Windows/PowerShell in the picture)
0. Use something like [`update-informer`](https://crates.io/crates/update-informer) which periodically checks for updates.
0.  When an update is available, they're told to repeat the installation process.

So, I can see we can start a couple of users off with the Circle-CI workflow, without any of the nice installation instructions, or update-informers.

We can build in nice instructions and update flows focussing on Github releases, up until [SYNC-3706](https://mozilla-hub.atlassian.net/browse/SYNC-3706) is fixed, then switch the install script and the update informer to check there instead. 

Aternatives considered:

1. maintain a version string in the `Cargo.toml` of `nimbus-cli` and check the version on`main`, then download from taskcluster. Good: allows `nimbus-cli` to release off train. Bad: easy to get the `main` and task cluster out of sync shortly after an increment of the version.
2. use https://crates.io : Good: tooling already built, allows `nimbus-cli` to release off train. Bad: forces QA and devs to have Rust tooling.

Other thoughts:

1. Should the `nimbus-cli` take care of unpacking the zip file, and replacing itself? Sounds risky, but cuts out another step.
2. How might we choose the right place to put the `nimbus-cli` binary? This would be the job of an **installer**.
3. Should we build installers (perhaps with [`cargo bundle`](https://crates.io/crates/cargo-bundle))

**Comment by jhugman** [comment]
At the moment, no one has the binary.

For now, I'm expecting QA to find some things they don't like, bugs, etc which will require small amounts of ongoing development, but long term, I'm not expecting frequent updates.

I think my ideal would be:

0. The `nimbus-cli` users to have access to a bash shell.
0. They follow instructions on https://experimenter.info to install, hopefully `curl https://raw.githubusercontent.com/mozilla/application-services/tools/get-nimbus-cli.sh | sh` (hopefully, because this won't be so clean with Windows/PowerShell in the picture)
0. Use something like [`update-informer`](https://crates.io/crates/update-informer) which periodically checks for updates.
0.  When an update is available, they're told to repeat the installation process.

So, I can see we can start a couple of users off with the Circle-CI workflow, without any of the nice installation instructions, or update-informers.

We can build in nice instructions and update flows focussing on Github releases, up until [SYNC-3706](https://mozilla-hub.atlassian.net/browse/SYNC-3706) is fixed, then switch the install script and the update informer to check there instead. 

Aternatives considered:

1. maintain a version string in the `Cargo.toml` of `nimbus-cli` and check the version on`main`, then download from taskcluster. Good: allows `nimbus-cli` to release off train. Bad: easy to get the `main` and task cluster out of sync shortly after an increment of the version.
2. use https://crates.io : Good: tooling already built, allows `nimbus-cli` to release off train. Bad: forces QA and devs to have Rust tooling.

Other thoughts:

1. Should the `nimbus-cli` take care of unpacking the zip file, and replacing itself? Sounds risky, but cuts out another step.
2. How might we choose the right place to put the `nimbus-cli` binary? This would be the job of an **installer**.
3. Should we build installers (perhaps with [`cargo bundle`](https://crates.io/crates/cargo-bundle))

**Comment by bendk** [comment]
I'm working on fixing the nimbus-fml build in https://github.com/mozilla/application-services/pull/5543.  Let's land this one and I'll try to update that to also build nimbus-cli.

**Comment by jhugman** [comment]
Thanks Ben!

**Pull request merged**
