### PR TITLE
Fix gradle builds for Apple Silicon running arm64 JDKs

### LINKED ISSUE #4665: Add support for M1 Macbook desktop testing
Building A-S for Android needs some updates to be out-of-the-box compatible with M1 Macbooks. I'm trying to work through the issues locally, but am new to the project so it's a bit slow going. I'll keep this issue updated with blockers and their solutions as I encounter them:

1. Android `sdkmanager` command line tools required by build not compatible with M1. The error I saw was `Could not find or load main class com.android.sdklib.tool.sdkmanager.SdkManagerCli`, but there may be others. See [this SO post](https://stackoverflow.com/questions/69869181/error-about-android-studio-on-macbook-m1-an-error-occurred-while-trying-to-comp?noredirect=1&lq=1).
  * Use Android Studio Canary version to download the required SDK tools. If done correctly, the executable will be found in: `Users/<user>/Library/Android/sdk/cmdline-tools/latest/bin/sdkmanager`.
1. Running `./libs/verify-android-environment.sh` fails with `Cannot get property 'nativeRustTarget' on extra properties extension as it does not exist`.
  * Add the following case to the nativeRustTarget switch:

```
switch (DefaultPlatform.RESOURCE_PREFIX) {
     case 'darwin':
     case 'darwin-x86-64':
+    case 'darwin-aarch64':
         ext.nativeRustTarget = 'darwin'
         break
     case 'linux-x86-64':
```

1. Re-running `./libs/verify-android-environment.sh` appears to have another error:

```
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

Traceback (most recent call last):
  File "/usr/local/bin/gyp", line 11, in <module>
    load_entry_point('gyp==0.1', 'console_scripts', 'gyp')()
  File "/Library/Python/2.7/site-packages/gyp-0.1-py2.7.egg/gyp/__init__.py", line 552, in script_main
    return main(sys.argv[1:])
  File "/Library/Python/2.7/site-packages/gyp-0.1-py2.7.egg/gyp/__init__.py", line 545, in main
    return gyp_main(args)
  File "/Library/Python/2.7/site-packages/gyp-0.1-py2.7.egg/gyp/__init__.py", line 530, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "/Library/Python/2.7/site-packages/gyp-0.1-py2.7.egg/gyp/generator/ninja.py", line 2493, in GenerateOutput
    pool.map(CallGenerateOutputForConfig, arglists)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
AttributeError: 'NoneType' object has no attribute 'groups'
```

* This error can allegedly be ignored according to [this issue](https://github.com/nodejs/node-gyp/issues/569) and [this issue](https://github.com/nodejs/node-gyp/issues/1464)

1. Running `cargo test` causes the following error. This happens with different crates on subsequent runs:

    error: failed to run custom build command for `sql-support v0.1.0 (/Users/matthewtighe/dev/application-services/components/support/sql)`
    
    Caused by:
      process didn't exit successfully: `/Users/matthewtighe/dev/application-services/target/debug/build/sql-support-22f2ec6dbcbc1fcd/build-script-build` (exit status: 101)
      --- stdout
      cargo:rerun-if-changed=build.rs
      cargo:rerun-if-env-changed=NSS_DIR
    
      --- stderr
      thread 'main' panicked at 'It looks like NSS is not built. Please run `libs/verify-[platform]-environment.sh` first!', components/support/rc_crypto/nss/nss_build_common/src/lib.rs:55:9
      note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    warning: build failed, waiting for other jobs to finish...
    error: build failedMy guess now is that `nss` is being compiled for `x86_64`  instead of `aarch64`, but I'm still trying to figure out how to check/change that.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2904)
┆epic: local development, ci and release (backlog)
┆sprintEndDate: 2022-02-03

### PR DESCRIPTION
**Pull request by skhamis**
fixes #4665 

### To Test (Intel or M1 Mac)
1. Delete your libs/desktop folder (should be only darwin in there)
2. If you have any `rust.targets` in your `local.properties` update (or just comment out for now):
 - Remove any `darwin` targets
 - update to one of the new darwin-specific architectures
2. Run `./libs/verify-desktop-environment.sh`
3. also run `./build-all.sh android` (shouldn't need rebuild but just incase)
3. you should now see libs/desktop/darwin-{your-arch}
4. in the top level of the project, run `./gradlew assembleDebug`
5. using local-published flow, ensure android-components can also build successfully
6. using local-published flow, ensure fenix can also build successfully 

- [x] Need to confirm it still works on Intel (will need to clear out libs/desktop and rebuild NSS/SQLCipher)
- [X] Need to be able to successfully build android-components -> fenix with no issues

### Pull Request checklist ###

- [ ] **Quality**: This PR builds and tests run cleanly
  - Note:
    - For changes that need extra cross-platform testing, consider adding `[ci full]` to the PR title.
    - If this pull request includes a breaking change, consider [cutting a new release](https://github.com/mozilla/application-services/blob/main/docs/howtos/cut-a-new-release.md) after merging.
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes a changelog entry in [CHANGES_UNRELEASED.md](../CHANGES_UNRELEASED.md) or an explanation of why it does not need one
  - Any breaking changes to Swift or Kotlin binding APIs are noted explicitly
- [ ] **Dependencies**: This PR follows our [dependency management guidelines](https://github.com/mozilla/application-services/blob/main/docs/dependency-management.md)
  - Any new dependencies are accompanied by a summary of the due dilligence applied in selecting them.

### CODE REVIEW

**Comment by skhamis** [comment]
@tarikeshaq would you mind following the instructions to test that this works on Intel?
@MatthewTighe would you mind also following the instructions to test that this works on your M1 (will need to ensure your JDK is arm64)

**Review by tarikeshaq — APPROVED** [review]
Tested it on my Intel machine! app services builds all the way across the local development flow to fenix/android components. As we debugged yesterday, I had a `rust.targets` in my `local.properties` and I need to replace `darwin` with `darwin-x86-64`.

We should probably the docs in https://github.com/mozilla/application-services/blob/main/docs/howtos/locally-published-components-in-fenix.md to reference the new `darwin-x86-64` and `darwin-aarch64` targets instead of `darwin`

**Comment by skhamis** [comment]
This is blocked until:
- https://github.com/mozilla-mobile/android-components/pull/11626
or
- https://github.com/mozilla-mobile/android-components/pull/11516

land as any M1s hoping to build a-s and then use the locally published flow in a-c will run into issues with the kotlin library `room`. While the first PR is much smaller, there is issues raised on the a-c team being that it's a pre-release version and moving to the next stable release will require kotlin 1.6 (second PR).

**Comment by skhamis** [comment]
While this fixes it in a-s, there will be an issue in a-c with the `room` library so I won't announce that M1s can use native arm64 JDKs, however given that this is still needed on our side -- I'll land it once all tests pass and let a-c chart the path to fixing it on their side based on their timetables.

**Pull request merged**
