### PR TITLE
build-sqlcipher-ios.sh: fx ios needs threadsafe=2 set

### PR DESCRIPTION
**Pull request by garvankeeley**
Firefox iOS can use the same sqlcipher as the Megazord as long as sqlite is set to full multi-thread mode.

### CODE REVIEW

**Comment by garvankeeley** [comment]
Right we also need to `"PRAGMA cipher_memory_security = OFF;"`
I think that would fix a general slowness; the app is written to expect that it can do concurrent reads for quick small things while the db is bogged down doing heavy sync ops on the read/write thread. I suspect both are the cause, one problem is the slower DB ops, and other the UI pausing to do an update for a quick state check. We also need to fix up the fact that any DB op can result in a paused UI state without the UI providing some feedback like a spinner.

**Comment by thomcc** [comment]
> the app is written to expect that it can do concurrent reads for quick small things while the db is bogged down doing heavy sync ops on the read/write thread

These are on separate database connections, so the setting of SQLITE_THREADSAFE should make no difference.

**Comment by garvankeeley** [comment]
Oh dear, I was going off the work @justindarc did when we added a concurrent connection, and assumed this was part of that requirement. Let's not land until we figure out the need for this.
Also, I am not sure we have reproduced the perf problem locally yet.

**Comment by thomcc** [comment]
E.g. if you expect to be making separate reads on the same connection, there's additional synchronization preventing that on both the rust side and the swift side.

Uncontended mutex acquisition being cheap (see mutex microbenchmarks, or any of those sets of 'perf numbers every programmer should know') means this redundant locking on both swift and rust isn't a big deal (and it's necessary in both places for correctness in edge cases).

**Comment by thomcc** [comment]
Eh, it doesn't hurt to add this, since we know we're preventing concurrent reads on the same connection already. I'm OK landing it.

**Comment by garvankeeley** [comment]
> E.g. if you expect to be making separate reads on the same connection, there's additional synchronization preventing that on both the rust side and the swift side.

IIUC, we have `browser.db` (our old Sync/history/bookmarks) database with a single connection, and we have a reader/writer queue for various heavy ops, and a second one for quickie read-only things like 'is this page bookmarked' . When the app boots and Sync runs, even though it runs in chunks, it is blocking doing quick state reads and makes the app less responsive.

**Comment by justindarc** [comment]
There's conflicting info out there about the two threadsafe modes. Regardless, we already are coordinating access to the DB connections to prevent unsafe accesses, so it shouldn't matter. That being said, the built-in sqlite library that comes with iOS uses `SQLITE_THREADSAFE=2`. Also, if we're already safeguarding accesses to the DB connections, it would seem to be overkill to also have SQLite serializing accesses and so I think `SQLITE_THREADSAFE=2` is the correct setting to use here.

**Comment by rfk** [comment]
> Firefox iOS can use the same sqlcipher as the Megazord

This is a great discussion that we should definitely have, but I'm hesitant about rushing into this kind of sharing if we don't have to.  It's not clear to me whether we've sufficiently thought through all the implications and details, and I worry that we would set ourselves up for a long tail of unintended consequences.

Does Firefox for iOS have a work-around to continue using the builtin sqlite etc for things other than logins? This seems likely to be the safest approach in the short term, until we take a step back and figure out how to *deliberately* share low-level sqlite functionality between components and the app.

> however making this change doesn't bother me.

To be completely clear, I'm also fine with the individual change discussed in this PR.  I have a broader concern about responding to a leaky abstraction by making it even leakier (and it's very possible that I just don't have enough context to understand the issue properly, this is mostly a gut reaction).

**Comment by thomcc** [comment]
In general I agree and think firefox iOS should continue using its own sqlite if possible. That said,

> responding to a leaky abstraction by making it even leakier

Isn't really accurate. This is more removing an additional layer of locking when we already have two layers of locking. Which is also why I don't expect it to matter.

**Comment by justindarc** [comment]
We have a workaround for the time being, so I don't think we need to solve everything immediately. For now, we're just going to build our own sqlite for all the existing iOS code to link to. The two sqlites seem to be co-existing fine, so I think we're good. Also, long story, but this isn't the first time we've had two copies of sqlite in our app at once 😳

**Comment by garvankeeley** [comment]
Closing, due to a workaround and this being a temporary problem, but lots of good discussion stimulated!

Summary
- because we have new Rust db code and *also* old History+Bookmarks db –and it seemed like the latter was based on using "threadsafe=2" (which I am not convinced was a necessary approach reading the comments)– rather than have 2 sqlite libs in the app, we thought we would use the Rust db one.
- we have a workaround linking in another version of sqlite 
- in future, all db code will go through rust component and having 2 sqlite implementations be a non-issue.
- the rationale for threadsafe=2 was for perf, and new Rust lib will hopefully have a new (and better!) approach. 
- the perf issue to keep in mind is that syncing at app startup is *very* heavy disk I/O, and write operations can take unpredictably long (for instance due to write contention with the all the other OS processes), so even chunking the writes as we do now (and allowing for other DB ops to run between chunks) makes for a sub-par user experience. We need to be able to read from the DB concurrently with the r/w sync operation happening. Reads, unlike write ops, are highly-deterministic perf-wise on iOS.

**Pull request closed without merging**
