### PR TITLE
Add musl binary for alpine linux [ci full]

### PR DESCRIPTION
**Pull request by jhugman**
Fixed [EXP-3777](https://mozilla-hub.atlassian.net/browse/EXP-3777).

This PR does a four related things:

- adds a `musl` build for `nimbus-cli`
- adds an option to the `install-nimbus-cli.sh` script to select a different binary than the one derived from the environment.
- make the `musl` flavor of the `nimbus-cli` the default selected by the `install-nimbus-cli.sh` for linux
- change the linux build of `nimbus-fml` to use `musl`

This last one has risk associated with it: if things go wrong then it breaks the build for Fenix. It is not expected to break the build.

### Pull Request checklist ###

- **Breaking changes**:  This PR follows our [breaking change policy](https://github.com/mozilla/application-services/blob/main/docs/howtos/breaking-changes.md)
  - [ ] This PR follows the breaking change policy:
     - This PR has no breaking API changes, or
     - There are corresponding PRs for our consumer applications that resolve the breaking changes and have been approved
- [ ] **Quality**: This PR builds and tests run cleanly
  - Note:
    - For changes that need extra cross-platform testing, consider adding `[ci full]` to the PR title.
    - If this pull request includes a breaking change, consider [cutting a new release](https://github.com/mozilla/application-services/blob/main/docs/howtos/cut-a-new-release.md) after merging.
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes a changelog entry in [CHANGELOG.md](../CHANGELOG.md) or an explanation of why it does not need one
  - Any breaking changes to Swift or Kotlin binding APIs are noted explicitly
- [ ] **Dependencies**: This PR follows our [dependency management guidelines](https://github.com/mozilla/application-services/blob/main/docs/dependency-management.md)
  - Any new dependencies are accompanied by a summary of the due dilligence applied in selecting them.

[Branch builds](https://github.com/mozilla/application-services/blob/main/docs/howtos/branch-builds.md): add `[firefox-android: branch-name]` to the PR title.

### CODE REVIEW

**Review by bendk — COMMENTED** [review]
Looks good to me.  Can you fix the spelling mistake are re-push?  I added `[ci full]` so that the taskcluster code will get some more testing.

**Comment by bendk** [comment]
Looks like CI needs gcc-musl, I think something like this should fix things:

```
diff --git a/taskcluster/docker/linux/Dockerfile b/taskcluster/docker/linux/Dockerfile
index b6c15749b..b9f18b3f7 100644
--- a/taskcluster/docker/linux/Dockerfile
+++ b/taskcluster/docker/linux/Dockerfile
@@ -77,6 +77,8 @@ RUN apt-get update -qq \
         # To install UTF-8 locales.
         locales \
         # For `cc` crates; see https://github.com/jwilm/alacritty/issues/1440.
+        # Nimbus binaries
+        musl-tools \
         # <TODO: Is this still true?>.
         g++ \
         # taskcluster > mohawk > setuptools.
```

**Comment by jhugman** [comment]
> Looks like CI needs gcc-musl, I think something like this should fix things:

YES! This fixed it! Thank you.

**Review by bendk — APPROVED** [review]
Looks good to me.

**Pull request merged**
