### PR TITLE
Fix #4317 - firefox-iOS build dependency on xcode 12.5.1

### LINKED ISSUE #4317: Firefox-iOS fails to build due to A-S dependency on Xcode 12.5.1
Bitrise (CI used for firefox-iOS) has automatically updated to xcode 12.5.1 and the app fails to build:
Downloading application-services binary at "v79.0.2"
***  Skipped installing application-services binary due to the error:
	"Incompatible Swift version - framework was built with 5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55) and the local version is 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57)."

See firefox-iOS issue: https://github.com/mozilla-mobile/firefox-ios/issues/8797 for more details.

Thanks

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2680)

### PR DESCRIPTION
**Pull request by isabelrios**
Not sure if that is the only change needed in order to fix issue #4317. Trying to help with this

### Pull Request checklist ###

- [ ] **Quality**: This PR builds and tests run cleanly
  - Note:
    - For changes that need extra cross-platform testing, consider adding `[ci full]` to the PR title.
    - If this pull request includes a breaking change, consider [cutting a new release](https://github.com/mozilla/application-services/blob/main/docs/howtos/cut-a-new-release.md) after merging.
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes a changelog entry in [CHANGES_UNRELEASED.md](../CHANGES_UNRELEASED.md) or an explanation of why it does not need one
  - Any breaking changes to Swift or Kotlin binding APIs are noted explicitly
- [ ] **Dependencies**: This PR follows our [dependency management guidelines](https://github.com/mozilla/application-services/blob/main/docs/dependency-management.md)
  - Any new dependencies are accompanied by a summary of the due dilligence applied in selecting them.

### CODE REVIEW

**Review by mhammond — APPROVED** [review]
👍

**Comment by isabelrios** [comment]
Thanks for merging this @mhammond. Do you know if/when this may be included in a dot release? Thanks!

**Comment by hornhuang** [comment]
when i try again, it always failed 

github "mozilla/application-services"      "v80.0.1"

`
	/usr/bin/xcrun xcodebuild -project /Users/sunshine/Documents/GitHub/firefox-ios/Carthage/Checkouts/application-services/megazords/ios/MozillaAppServices.xcodeproj -scheme MozillaAppServices -configuration Release -derivedDataPath /Users/sunshine/Library/Caches/org.carthage.CarthageKit/DerivedData/12.5.1_12E507/application-services/v80.0.1 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive VALIDATE_WORKSPACE=NO -archivePath /var/folders/xp/p911thvj2zj7bwyxv2rjrsc80000gn/T/application-services SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/sunshine/Documents/GitHub/firefox-ios/Carthage/Checkouts/application-services)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/xp/p911thvj2zj7bwyxv2rjrsc80000gn/T/carthage-xcodebuild.IWveTe.log
mv: rename Carthage/Build/iOS/MozillaAppServices.framework/sdk_generator.sh to ./sdk_generator.sh: No such file or directory
`

**Comment by isabelrios** [comment]
> when i try again, it always failed
> 
> github "mozilla/application-services" "v80.0.1"
> 
> `
> /usr/bin/xcrun xcodebuild -project /Users/sunshine/Documents/GitHub/firefox-ios/Carthage/Checkouts/application-services/megazords/ios/MozillaAppServices.xcodeproj -scheme MozillaAppServices -configuration Release -derivedDataPath /Users/sunshine/Library/Caches/org.carthage.CarthageKit/DerivedData/12.5.1_12E507/application-services/v80.0.1 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive VALIDATE_WORKSPACE=NO -archivePath /var/folders/xp/p911thvj2zj7bwyxv2rjrsc80000gn/T/application-services SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/sunshine/Documents/GitHub/firefox-ios/Carthage/Checkouts/application-services)
> 
> This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/xp/p911thvj2zj7bwyxv2rjrsc80000gn/T/carthage-xcodebuild.IWveTe.log
> mv: rename Carthage/Build/iOS/MozillaAppServices.framework/sdk_generator.sh to ./sdk_generator.sh: No such file or directory
> `

Are you on Xcode 12.5.1? it should work when running the project on that xcode version, that's the one running successfully now on our CI.

**Pull request merged**
