### PR TITLE
Update rusqlite to 0.24.1 and libsqlite3-sys to 0.20.1

### PR DESCRIPTION
**Pull request by mhammond**
As @thomcc kindly flagged in #3632 - once approved I'll merge this into the vendor-mc/78 and then re-vendor that branch into m-c.

### CODE REVIEW

**Review by rfk — APPROVED** [review]
👍

**Comment by rfk** [comment]
@mhammond oh, looks like you need to regenerate the dependency list using `./tools/regenerate_dependency_summaries.sh`; LMK if it gives you any trouble and I can take a look, sometimes it only works correctly when run on a Mac, for reasons.

**Comment by mhammond** [comment]
> sometimes it only works correctly when run on a Mac, for reasons.

Right - the current failure is for packages used only by the iOS megazord :/ I can fix that.

**Comment by mhammond** [comment]
Test failure is #3627, so merging...

**Pull request merged**
