### PR TITLE
Don't provide a stdc++ on Windows

### PR DESCRIPTION
**Pull request by Dexterp37**
In the current state of things, the build will fail on Windows, because it won't find the stdlib.

The rustc docs mention (but I'm struggling to find the docs again) that, on Windows, this should not be provided.
It fixes the compilation for me, locally.

Update: while I can't find the documentation page that @badboy sent me a while back, he was kind enough to provide [this example](https://github.com/rust-lang/rust/blob/87dce6e8dfdae605c9c2a713cf0133066a52022a/compiler/rustc_llvm/build.rs#L288-L303) of how rustc skips everything when the target is msvc.

### Pull Request checklist ###

- [ ] **Quality**: This PR builds and tests run cleanly
  - Note:
    - For changes that need extra cross-platform testing, consider adding `[ci full]` to the PR title.
    - If this pull request includes a breaking change, consider [cutting a new release](https://github.com/mozilla/application-services/blob/main/docs/howtos/cut-a-new-release.md) after merging.
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes a changelog entry in [CHANGES_UNRELEASED.md](../CHANGES_UNRELEASED.md) or an explanation of why it does not need one
  - Any breaking changes to Swift or Kotlin binding APIs are noted explicitly
- [ ] **Dependencies**: This PR follows our [dependency management guidelines](https://github.com/mozilla/application-services/blob/main/docs/dependency-management.md)
  - Any new dependencies are accompanied by a summary of the due dilligence applied in selecting them.

### CODE REVIEW

**Comment by mhammond** [comment]
How are you building locally? I seem unable to get nss and sqcipher built both with and without this patch. I've been forced into wsl for the last few years, so would love to discover the secret-sauce here.

**Comment by Dexterp37** [comment]
> How are you building locally? I seem unable to get nss and sqcipher built both with and without this patch. I've been forced into wsl for the last few years, so would love to discover the secret-sauce here.

I'm using the lines from https://github.com/mozilla-services/remote-settings-client/blob/6bb0b0d1f0a9243ffe4a58d81f682ba721e226f2/.circleci/config.yml#L23-L52 :D Calling them locally in WSL

**Comment by mhammond** [comment]
ha - so using WSL to cross-compile native windows binaries! For interest, what do you do with them? I just tend to stay in the WSL environment to run as well so I don't think this will actually help my workflow in practice. Either way, this LGTM, but I'll leave the r+ to @leplatrem

**Review by leplatrem — APPROVED** [review]
I don't have Windows at hand, but if that change works for you, I have nothing against it! :shrug:
(the `else` here was for Mac, where the stdlib is available as `c++` instead of `stdc++`)

**Comment by Dexterp37** [comment]
Gah, I don't have time sadly to chase the iOS problems. I'm also happy to keep using this patch locally by changing the `Cargo.toml` as follow (for future reference to anyone stumbling upon this, since it took us some time to figure out):

```toml
# Patch NSS until fixed by a-s
[patch.'https://github.com/mozilla/application-services']
nss_build_common = { path = "patches/nss_build_common" }
```

**Pull request closed without merging**
