### PR TITLE
Update NSS to version 3.84

### PR DESCRIPTION
**Pull request by rvandermeulen**
I could use some help getting the pre-built macOS & Windows archives uploaded to S3 rather than going through the steps of requesting access for myself to do it. Here's a link to the NSS Try push:
https://treeherder.mozilla.org/jobs?repo=nss-try&revision=9930fc7c03092ebc139d0f613d3eeb4cd2c07c94

### CODE REVIEW

**Comment by rvandermeulen** [comment]
Blech, iOS bustage from [bug 1655493](https://bugzilla.mozilla.org/show_bug.cgi?id=1655493) it appears.
```
libtool: link: /Applications/Xcode-13.4.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -dynamiclib  -o .libs/libsqlcipher.0.dylib  .libs/sqlite3.o   -L/Users/distiller/project/libs/ios/x86_64/nss/lib -lz -lcertdb -lcerthi -lcryptohi -lfreebl_static -lnspr4 -lnss_static -lnssb -lnssdev -lnsspki -lnssutil -lpk11wrap_static -lplc4 -lplds4 -lsoftokn_static -lgcm-aes-x86_c_lib -lhw-acc-crypto-avx -lhw-acc-crypto-avx2  -arch x86_64 -isysroot /Applications/Xcode-13.4.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk -mios-version-min=11.0   -install_name  /usr/local/lib/libsqlcipher.0.dylib -compatibility_version 9 -current_version 9.6 -Wl,-single_module
Undefined symbols for architecture x86_64:
  "_SHA256_Compress_Native", referenced from:
      _SHA256_Begin in libfreebl_static.a(freebl_static.sha512.o)
      _SHA224_Begin in libfreebl_static.a(freebl_static.sha512.o)
  "_SHA256_Update_Native", referenced from:
      _SHA256_Begin in libfreebl_static.a(freebl_static.sha512.o)
      _SHA224_Begin in libfreebl_static.a(freebl_static.sha512.o)
ld: symbol(s) not found for architecture x86_64
```

**Comment by rvandermeulen** [comment]
Alright, I think this is ready for review. The failing macOS and Windows toolchain jobs are expected because the pre-built artifacts haven't been uploaded to the S3 bucket yet. We can rerun them once they've been uploaded by someone ([link to Try push](https://treeherder.mozilla.org/jobs?repo=nss-try&revision=9930fc7c03092ebc139d0f613d3eeb4cd2c07c94)) with the permissions to do so.

**Comment by skhamis** [comment]
I'd love to help out with this! Though I'll need to find out who/how to access to that S3 bucket (most of us probably don't access it very often)

**Comment by rvandermeulen** [comment]
New NSS Try push for the 3.84 binaries:
https://treeherder.mozilla.org/jobs?repo=nss-try&revision=593b4567f80830f1c118d6bc2785d21b2817d484

**Comment by rvandermeulen** [comment]
Note that version 3.85 has been tagged now, but I'm going to hold off on further updates to this PR until #5210 is sorted out.

**Comment by skhamis** [comment]
This will most likely be superseded by https://github.com/mozilla/application-services/pull/5254 -- but i'll let you close it!

**Comment by rvandermeulen** [comment]
Nice!

**Pull request closed without merging**
