### PR TITLE
Update iOS docs for adding a Rust component; install Apple silicon iOS Simulator target. [ci full]

### PR DESCRIPTION
**Pull request by linabutler**
Hi! 👋🏼 I went through the (fantastic! 🤩) instructions for adding a Rust component, and updated the ones for iOS based on my experience. (I also had to install the `aarch64-apple-ios-sim` target on my M1 Mac, or the framework wouldn't build at all). Please take a look whenever it's convenient, thanks!

[Rendered view](https://github.com/mozilla/application-services/blob/33dac11c0640bc3250e8d0ed707950c1e03b85db/docs/howtos/adding-a-new-component.md)

(No changes to the code, but I added `[ci full]` just in case, since I did change the CI bootstrapping script).

### Pull Request checklist ###

- [ ] **Quality**: This PR builds and tests run cleanly
  - Note:
    - For changes that need extra cross-platform testing, consider adding `[ci full]` to the PR title.
    - If this pull request includes a breaking change, consider [cutting a new release](https://github.com/mozilla/application-services/blob/main/docs/howtos/cut-a-new-release.md) after merging.
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes a changelog entry in [CHANGES_UNRELEASED.md](../CHANGES_UNRELEASED.md) or an explanation of why it does not need one
  - Any breaking changes to Swift or Kotlin binding APIs are noted explicitly
- [x] **Dependencies**: This PR follows our [dependency management guidelines](https://github.com/mozilla/application-services/blob/main/docs/dependency-management.md)
  - Any new dependencies are accompanied by a summary of the due dilligence applied in selecting them.

[Branch builds](https://github.com/mozilla/application-services/blob/main/docs/howtos/branch-builds.md): add `[ff-android: firefox-android-branch-name]` and/or `[fenix: fenix-branch-name]` to the PR title.

### CODE REVIEW

**Review by tarikeshaq — DISMISSED** [review]
WOHOO thanks a ton, @linabutler!! :shipit:

**Comment by linabutler** [comment]
Yaaay thank you so much for the speedy review, @tarikeshaq! 🙏🏼

**Review by tarikeshaq — APPROVED** [review]
Approving again, because mergify did the thing again 😬

**Comment by tarikeshaq** [comment]
I'll land this as long as the required CI passes, no need for the android builds to run! I'll also get @linabutler added to the github team that prevents mergify from dismissing reviews and allows landing PRs

**Pull request merged**
