### PR TITLE
[ci full] Remove unused unlock_notify feature from rustqlite.

### PR DESCRIPTION
**Pull request by emilio**
This was causing my build to fail locally with an undefined reference to
sqlite3_unlock_notify. It seems nothing makes use of this feature tho.

### Pull Request checklist ###

- [x] **Quality**: This PR builds and tests run cleanly
  - Note:
    - For changes that need extra cross-platform testing, consider adding `[ci full]` to the PR title.
    - If this pull request includes a breaking change, consider [cutting a new release](https://github.com/mozilla/application-services/blob/main/docs/howtos/cut-a-new-release.md) after merging.
- [x] **Tests**: No behavior change.
- [x] **Changelog**: Probably not worth putting this in the changelog.
- [x] **Dependencies**: This PR follows our [dependency management guidelines](https://github.com/mozilla/application-services/blob/main/docs/dependency-management.md)
  - Any new dependencies are accompanied by a summary of the due dilligence applied in selecting them.

### CODE REVIEW

**Comment by emilio** [comment]
Seems tests are unhappy. I'm not familiar with rustqlite or so, so happy to close this... But if somebody has any idea why my build fails locally otherwise I'm all ears :)

**Comment by emilio** [comment]
Ok, so this is really messy. I did a bit of digging with @bendk and I have various potential fixes, but not sure what the best path forward. Ben suggested asking @mhammond for advice, so that's what I'm doing.

The issue is that, in the context of the cargo workspace, some crates enable the `sqlcipher` feature, which causes the `bundled` feature not to work:

> For backwards compatibility, feature 'sqlcipher' overrides features 'bundled' and 'bundled-windows'. If you want a bundled build of SQLCipher (available for the moment only on Unix), use feature 'bundled-sqlcipher' or 'bundled-sqlcipher-vendored-openssl' to also bundle OpenSSL crypto.

So we end up using the bundled sqlite or not depending on how we build, which is... bad?

Additionally, the `sqlcipher` feature causes us to link into `libsqlcipher.so` instead of `libsqlite3.so`. The issue is that, on my system, `libsqlcipher.so` doesn't have `sqlite3_unlock_notify`, but `libsqlite3.so` does:

```
$ nm -gD /usr/lib/libsqlcipher.so | rg sqlite3_unlock
$ nm -gD /usr/lib/libsqlite3.so | rg sqlite3_unlock                                                                                                                                                                                      
000000000009c140 T sqlite3_unlock_notify
```

First potential fix is to make sure that we consistently use the bundled libsqlite, with something like this:

```diff
diff --git a/components/logins/Cargo.toml b/components/logins/Cargo.toml
index 557ae875..7a5f0dce 100644
--- a/components/logins/Cargo.toml
+++ b/components/logins/Cargo.toml
@@ -30,7 +30,7 @@ uniffi_macros = "^0.17"
 
 [dependencies.rusqlite]
 version = "0.27.0"
-features = ["sqlcipher", "limits", "unlock_notify"]
+features = ["sqlcipher", "limits", "unlock_notify", "bundled", "bundled-sqlcipher"]
 
 [build-dependencies]
 uniffi_build = { version = "^0.17", features=["builtin-bindgen"] }
```

Second potential fix, more in the vein of the current `build.rs` hack, is to make sure we actually link in `libsqlite3.so`:

```diff
diff --git a/components/support/sql/build.rs b/components/support/sql/build.rs
index feeb5ca5..4611c62b 100644
--- a/components/support/sql/build.rs
+++ b/components/support/sql/build.rs
@@ -11,6 +11,7 @@
 
 fn main() {
     println!("cargo:rerun-if-changed=build.rs");
+    println!("cargo:rustc-link-lib=sqlite3");
 
     // If NSS_DIR isn't set, we don't really care, ignore the Err case.
     let _ = nss_build_common::link_nss();
```

Both fixes probably need tweaks for non-UNIX platforms... But anyways, the issue is that `cargo test` from the root of the workspace ends up using system libraries, and my system `libsqlcipher` doesn't have the `unlock_notify` functionality.

@mhammond, do you have any thoughts on what's preferred here?

**Comment by emilio** [comment]
I reported https://bugs.archlinux.org/task/74622 for my distro to enable the relevant feature in the sqlcipher package as well...

**Comment by emilio** [comment]
Ben additionally mentioned that we have an env variable to link `sqlcipher` to `libs/desktop/linux-x86-64/sqlcipher/lib`. However that doesn't seem to be working quite right because this is the output of the build script:

<details>

```
$ cat libsqlite3-sys-f430f57b96952fed/output                                                                                                                                                                                             
cargo:rerun-if-env-changed=SQLCIPHER_INCLUDE_DIR
cargo:rerun-if-env-changed=SQLCIPHER_LIB_DIR
cargo:rerun-if-env-changed=SQLCIPHER_STATIC
cargo:link-target=sqlcipher
cargo:rerun-if-env-changed=SQLCIPHER_NO_PKG_CONFIG
cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
cargo:rerun-if-env-changed=HOST_PKG_CONFIG
cargo:rerun-if-env-changed=PKG_CONFIG
cargo:rerun-if-env-changed=SQLCIPHER_STATIC
cargo:rerun-if-env-changed=SQLCIPHER_DYNAMIC
cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
cargo:rerun-if-env-changed=PKG_CONFIG_PATH
cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
cargo:rerun-if-env-changed=SYSROOT
cargo:rerun-if-env-changed=SQLCIPHER_STATIC
cargo:rerun-if-env-changed=SQLCIPHER_DYNAMIC
cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
cargo:rustc-link-search=native=/usr/lib
cargo:rustc-link-lib=sqlcipher
cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
cargo:rerun-if-env-changed=HOST_PKG_CONFIG
cargo:rerun-if-env-changed=PKG_CONFIG
cargo:rerun-if-env-changed=SQLCIPHER_STATIC
cargo:rerun-if-env-changed=SQLCIPHER_DYNAMIC
cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
cargo:rerun-if-env-changed=PKG_CONFIG_PATH
cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
```

</details>

So looking into the sys crate build script:

https://github.com/rusqlite/rusqlite/blob/b411d27b54fd72320992bbb8bf9ff863b505fef8/libsqlite3-sys/build.rs#L415-L425

It uses that env var to do pkg-config shenanigans. There's no pkgconfig file in `libs/desktop/linux-x86-64/sqlcipher/lib`, so maybe it succeeds and returns my system's `libsqlcipher`?

**Comment by emilio** [comment]
That seems to be what's going on, if I remove my local `sqlcipher` binary, then it works...

**Comment by mhammond** [comment]
Sorry, I missed this conversation - sadly though I'm fairly clueless here. But I think we do not want to use a bundled sqlcipher, because we have used nss for the crypto rather than whatever it uses by default. It's for this reason we build it ourselves. I also don't expect *either* libsqlite.so or libsqlcipher.so to be used, and just `libs/desktop/linux-x86-64/sqlcipher/lib/libsqlcipher.a` statically linked (and, I assume, the "bundled" sqlite from rusqlite when used from other crates that don't use sqlcipher?) . It's for this reason we have so much pain on non-linux/mac environments - building this .a (and nss etc) is tricky - hence the only way I can use app-services on Windows is via WSL.

So I suspect the correct direction here would be to use the rusqlite `sqlcipher` feature - which is described as "looks for the SQLCipher library to link against instead of SQLite. This feature overrides bundled." - then all of our crates would be using sqlcipher (and IIRC, if you don't initialize the crypto in a db, then a sqlcipher db is just a plain old sqlite db) - which *sounds like* it would be a win, but sadly I'm really not sure about any of this.

I'm not sure exactly what context you are using this in, but sqlcipher is currently only used by our logins code to migrate old sqlcipher databases to a "plain" sqlite database and we manually encrypt certain columns manually. So we could probably add a feature-gate around that import capability, meaning consuming a-s with certain flags could avoid trying to use sqlcipher entirely (but would also fail to migrate old databases, so couldn't be enabled for our mobile clients). I'm not sure if this would help you or not.

**Comment by mhammond** [comment]
> It uses that env var to do pkg-config shenanigans. There's no pkgconfig file in `libs/desktop/linux-x86-64/sqlcipher/lib`, so maybe it succeeds and returns my system's `libsqlcipher`?

Right, yeah, it sounds like we should remove that capability entirely?

**Comment by mhammond** [comment]
We added `unlock_notify` in https://github.com/mozilla/application-services/issues/3287 - tl;dr of that is that it seems to be a feature not designed for direct consumption, but instead enables internal locking to perform better. IOW, removing `unlock_notify` will seem to work, but performance and actual functionality (ie, SQLITE_BUSY errors might happen more often) might take a hit.

Re pkg-config, rusqlite already has an issue for that at https://github.com/rusqlite/rusqlite/issues/510 - we could probably put a patch up to help with this (once we work out a good way to spell it), but I don't think we can do much about that in this specific issue - so I'm closing it.

**Pull request closed without merging**
