### PR TITLE
FTS prefix configuration ADR

### PR DESCRIPTION
**Pull request by bendk**
[Rendered version](https://github.com/bendk/application-services/blob/adr-fts-prefix/docs/adr/0008-fts-prefix-config.md)

The DISCO team discussed the FTS prefix setting and decided that we should do some benchmarking to see what the differences were.  This was actually not so simple and I fell down a bit of a rabbit hole, but I'm back with some benchmarks and a recommendation that I wrote up as an ADR.  The decision is still pending so please suggest other options if you think one of them would be better, it doesn't feel like a clear decision to me at all.

CC @clouserw

### Pull Request checklist ###

- **Breaking changes**:  This PR follows our [breaking change policy](https://github.com/mozilla/application-services/blob/main/docs/howtos/breaking-changes.md)
  - [x] This PR follows the breaking change policy:
     - This PR has no breaking API changes, or
     - There are corresponding PRs for our consumer applications that resolve the breaking changes and have been approved
- [x] **Quality**: This PR builds and tests run cleanly
  - Note:
    - For changes that need extra cross-platform testing, consider adding `[ci full]` to the PR title.
    - If this pull request includes a breaking change, consider [cutting a new release](https://github.com/mozilla/application-services/blob/main/docs/howtos/cut-a-new-release.md) after merging.
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes a changelog entry in [CHANGELOG.md](../CHANGELOG.md) or an explanation of why it does not need one
  - Any breaking changes to Swift or Kotlin binding APIs are noted explicitly
- [x] **Dependencies**: This PR follows our [dependency management guidelines](https://github.com/mozilla/application-services/blob/main/docs/dependency-management.md)
  - Any new dependencies are accompanied by a summary of the due diligence applied in selecting them.

[Branch builds](https://github.com/mozilla/application-services/blob/main/docs/howtos/branch-builds.md): add `[firefox-android: branch-name]` to the PR title.

### CODE REVIEW

**Comment by quiiver** [comment]
My take away from this is that it doesn't make a material difference in user experience if we use a prefix index at all. Really any query under 100ms will appear instantaneous from a user's perspective. Probably as the data in the fts index scales query optimization will come into play, however I would recommend option A as it results in the smallest db size.

**Comment by bendk** [comment]
I should also mention that there's a ton more benchmarking that could be done and I'm happy to test other suggestions.

**Comment by 0c0w3** [comment]
Thanks for putting this together. Overall it seems like a low-stakes decision since on one hand, as Wil said, so far these queries seem plenty fast enough even without indexes (I'm on a fast machine though), and on the other hand it doesn't appear that adding new prefix indexes increases the DB size all that much. Earlier I [found](https://docs.google.com/document/d/1vl-kPh2JSrA9ANlqzrE1XA1qpwXm0poXL-TE0s6EAQs/edit?usp=sharing) that each new prefix index even in a DB with 300k suggestions increased its size by only 3 MB. It might also be worth noting that desktop Firefox doesn't use indexes when it matches queries against history and bookmark titles in the urlbar. Not a reason Suggest shouldn't, just a comparison.

Wdyt about implementing [query telemetry](https://bugzilla.mozilla.org/show_bug.cgi?id=1908397) and using that data to make a decision? It could record word and char counts, whether a prefix query was triggered, etc.

**Comment by ncloudioj** [comment]
Thanks for putting things up together, Ben!

I am also a fan of starting off w/o prefix indices and instrumenting query metrics for future decision making.

Just curious, I assume the test queries are all positive queries (query hits), correct? Did you test any negative queries (query misses)?

**Comment by bendk** [comment]
I just pushed an update that adds benchmarks for ingestion time.  I completely forgot that I also ran those yesterday.  I also updated the decision to a) since that was the general consensus.  A sounds good to me as well, my one concern is when we move to mobile.  A 1ms benchmark result on my machine might be much more on an old phone with a cold cache.  But that's pretty speculative and it's very possible it won't be that much more and/or user's won't notice.

> Wdyt about implementing [query telemetry](https://bugzilla.mozilla.org/show_bug.cgi?id=1908397) and using that data to make a decision? It could record word and char counts, whether a prefix query was triggered, etc.

That would be very nice.  I'm not sure exactly how to measure and present all of that, but I'll try to include this data somehow.

> Just curious, I assume the test queries are all positive queries (query hits), correct? Did you test any negative queries (query misses)?

Yes, all queries were hits.

**Comment by bendk** [comment]
Seems like we have a decision.  What do you all think about updating the header to say approved and merging this one?

**Review by ncloudioj — APPROVED** [review]
Looks great. Option A is the winner for now.

**Pull request merged**
