### PR TITLE
update record_enrollment_status_telemetry to only send metrics for available experiments

### PR DESCRIPTION
**Pull request by jeddai**
### Pull Request checklist ###

- **Breaking changes**:  This PR follows our [breaking change policy](https://github.com/mozilla/application-services/blob/main/docs/howtos/breaking-changes.md)
  - [x] This PR follows the breaking change policy:
     - This PR has no breaking API changes, or
     - There are corresponding PRs for our consumer applications that resolve the breaking changes and have been approved
- [x] **Quality**: This PR builds and tests run cleanly
  - Note:
    - For changes that need extra cross-platform testing, consider adding `[ci full]` to the PR title.
    - If this pull request includes a breaking change, consider [cutting a new release](https://github.com/mozilla/application-services/blob/main/docs/howtos/cut-a-new-release.md) after merging.
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes a changelog entry in [CHANGELOG.md](../CHANGELOG.md) or an explanation of why it does not need one
  - Any breaking changes to Swift or Kotlin binding APIs are noted explicitly
- [x] **Dependencies**: This PR follows our [dependency management guidelines](https://github.com/mozilla/application-services/blob/main/docs/dependency-management.md)
  - Any new dependencies are accompanied by a summary of the due dilligence applied in selecting them.

[Branch builds](https://github.com/mozilla/application-services/blob/main/docs/howtos/branch-builds.md): add `[firefox-android: branch-name]` to the PR title.

### CODE REVIEW

**Review by travis79 — APPROVED** [review]
👍  Looks good to me, filtering the experiments to just the application and channel should remove the unwanted events, and bonus points for reusing a function that already exists (`is_experiment_available`).

**Comment by rvandermeulen** [comment]
@mergifyio backport release-v120

**Comment by rvandermeulen** [comment]
The last backport attempt hit conflicts. Trying again with another dependency backported first.

@mergifyio backport release-v120

**Comment by rvandermeulen** [comment]
@Mergifyio backport release-v120

**Pull request merged**
