### PR TITLE
WIP on logins API based on Mentat

### PR DESCRIPTION
**Pull request by ncalexan**

### CODE REVIEW

**Comment by mhammond** [comment]
I had a bit of a play with this.

I had to apply https://gist.github.com/mhammond/f320b744c986543e8d96b6f1923e8d29 which made it *almost* work. After that, I was left with many errors such as:

```
error[E0277]: the trait bound `mentat::MentatError: std::error::Error` is not satisfied

  --> sync15/passwords/ffi/src/lib.rs:81:21

   |

81 |           let store = mentat::Store::open_with_key(c_char_to_string(mentat_db_path),

   |  _____________________^

82 | |                                                  c_char_to_string(encryption_key))?;

   | |___________________________________________________________________________________^ the trait `std::error::Error` is not implemented for `mentat::MentatError`

   |

   = note: required because of the requirements on the impl of `std::convert::From<mentat::MentatError>` for `std::boxed::Box<std::error::Error>`

   = note: required by `std::convert::From::from`

```

which I believe is due to the fact that both mentat's and application-services's masters have the patch to move to failure, whereas your mentat branch is yet to incorporate that change.

Just for kicks, I made an attempt at merging mentat's master into your branch, which didn't seem to painful, and I successfully got that merge compiling.

So I went back to the application-services fork, and based on some chat's with Thom, I thought I'd try and avoid having so many of these crates directly reference mentat, by making the "pub use" the bits of mentat etc they need. So I ended up with the patch at https://gist.github.com/mhammond/0e17177d2876d0bcc91db2a5da4dc418 - note how there's now only 1 reference to mentat in 1 Cargo.toml (which that patch shows as pointing at my local tree where I did the merge)

Sadly though, I'm now ending up with various other build errors, such as:

```
error[E0308]: mismatched types
    --> logins/src/passwords.rs:1042:32
     |
1042 |                 builder.add(e, SYNC_PASSWORD_METADATA_TX.clone(), tx.clone())?;
     |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `mentat::KnownEntid`, found struct `mentat::Keyword`
     |
     = note: expected type `mentat::KnownEntid`
                found type `mentat::Keyword`
```

which is where I left things.

I hope some of the above is useful!

**Comment by mhammond** [comment]
Is there anything stopping us from landing this and addressing the error discussions in followup issues?

**Comment by thomcc** [comment]
Nope!

**Comment by ncalexan** [comment]
The parts that are going to land from this tree have landed.  The Android layer on top is under development in https://github.com/thomcc/application-services/commits/logins-android.

**Pull request closed without merging**
