### PR TITLE
Update Glean to v33.10.1

### PR DESCRIPTION
**Pull request by badboy**
### Pull Request checklist ###

- [ ] **Quality**: This PR builds and tests run cleanly
  - `automation/all_tests.sh` runs to completion and produces no failures
  - Note: For changes that need extra cross-platform testing, consider adding `[ci full]` to the PR title.
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes a changelog entry in [CHANGES_UNRELEASED.md](../CHANGES_UNRELEASED.md) or an explanation of why it does not need one
  - Any breaking changes to Swift or Kotlin binding APIs are noted explicitly
- [ ] **Dependencies**: This PR follows our [dependency management guidelines](https://github.com/mozilla/application-services/blob/main/docs/dependency-management.md)
  - Any new dependencies are accompanied by a summary of the due dilligence applied in selecting them.

### CODE REVIEW

**Comment by mhammond** [comment]
I'm a bit confused by the clippy failure - IIUC, `broken_intra_doc_links` is a rustdoc lint, so I guess it makes sense that it's "unknown" - but a quick google is failing to tell me how it should be resolved even though I'd expect it to be a very common problem. Any ideas @badboy?

**Comment by badboy** [comment]
> I'm a bit confused by the clippy failure - IIUC, `broken_intra_doc_links` is a rustdoc lint, so I guess it makes sense that it's "unknown" - but a quick google is failing to tell me how it should be resolved even though I'd expect it to be a very common problem. Any ideas @badboy?

That's a Rust lint.
Intra-doc linking [became stable in Rust 1.48.0](https://github.com/rust-lang/rust/blob/master/RELEASES.md#rustdoc).
Because it's treated as an `unknown-lints` in older Rust we didn't really break our own stated compatibility (1.43.0) but of course that doesn't help here as it causes issues for a-s.
Let me see how I can resolve that best.

**Comment by badboy** [comment]
I think the right solution here is to _not_ lint Glean code at all. Let's see if my fix does that.

Alternatively we need to add `-A unknown-lints` to the allow list.

**Comment by badboy** [comment]
There we go, excluding it didn't actually work (because Glean is not part of the workspace, but then I don't even understand why it is linting that. It shouldn't lint dependencies, should it?)

So I went  with allowing `unknown-lints` instead.

**Comment by badboy** [comment]
(with #3801 I'm going to remove the last commit here)

**Review by mhammond — APPROVED** [review]

**Pull request merged**
