### PR TITLE
Add the nimbus-gradle-plugin to application services

### PR DESCRIPTION
**Pull request by jeddai**
This will move the nimbus gradle plugin so it is built within application services instead of android components. Once a  build/release happens, we can remove the nimbus gradle plugin from and also use it in android components!

For [EXP-2637](https://mozilla-hub.atlassian.net/browse/EXP-2637)

### Pull Request checklist ###

- [x] **Quality**: This PR builds and tests run cleanly
  - Note:
    - For changes that need extra cross-platform testing, consider adding `[ci full]` to the PR title.
    - If this pull request includes a breaking change, consider [cutting a new release](https://github.com/mozilla/application-services/blob/main/docs/howtos/cut-a-new-release.md) after merging.
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes a changelog entry in [CHANGES_UNRELEASED.md](../CHANGES_UNRELEASED.md) or an explanation of why it does not need one
  - Any breaking changes to Swift or Kotlin binding APIs are noted explicitly
- [x] **Dependencies**: This PR follows our [dependency management guidelines](https://github.com/mozilla/application-services/blob/main/docs/dependency-management.md)
  - Any new dependencies are accompanied by a summary of the due dilligence applied in selecting them.

[Branch builds](https://github.com/mozilla/application-services/blob/main/docs/howtos/branch-builds.md): add `[ac: android-components-branch-name]` and/or `[fenix: fenix-branch-name]` to the PR title.

### CODE REVIEW

**Comment by jeddai** [comment]
We're pausing this work until the android repos have been consolidated into a monorepo
Details: https://mozilla-hub.atlassian.net/browse/EXP-2637?focusedCommentId=601496

**Review by jhugman — APPROVED** [review]
FWIW: this is a rubber stamp r+. ✅

**Comment by jeddai** [comment]
@jhugman a re-review would be appreciated if you have time. The new changes allow for the following:
- Local a-s can be used if set in the config
- The version of the plugin will be the version of the FML it checks for and downloads
- It _can_ be used in a-s modules, but we need to solve the non-android project issue first. I'd recommend that's in a separate ticket.

**Comment by jhugman** [comment]
> a re-review would be appreciated if you have time. 
Sure, I'll look at this on Monday.

>     * It _can_ be used in a-s modules, but we need to solve the non-android project issue first. I'd recommend that's in a separate ticket.

I agree with this.

**Comment by jeddai** [comment]
Logging off for the day, but I got it working! It now works in non-android projects, and works in a-s subprojects. I'll upload some patches tomorrow to help with testing.

**Comment by jeddai** [comment]
Here are some patches that can be used to test this change!
[patch_nimbus_changes_focus_and_android_components.patch](https://github.com/mozilla/application-services/files/10402269/patch_nimbus_changes_focus_and_android_components.patch)
[patch_nimbus_in_appservices.patch](https://github.com/mozilla/application-services/files/10402270/patch_nimbus_in_appservices.patch)

**Review by jhugman — APPROVED** [review]
I think this is ready to be landed. Well done it's been a hard slog getting here.

I don't think it's ready for general consumption yet, but that work should be done in other issues/tasks, and can be all done (hopefully) in the `NimbusGradlePlugin.groovy` file.

- [ ] `manifestFile` should be a relative path relative to the gradle file, rather than then project. (may be better to take a `File` instead of a `String`) - this is so adding nimbus to a component is easer.
- [ ] `destinationClass` is no longer needed, and should be removed.
- [ ] `assembleNimbusTools` is downloading a 0.0.1-SNAPSHOT version of nimbus-fml (STR a-c local properties autopublish.appservices is set, but `nimbus { appServicesDir }` is not); this is likely downloading the zip file from releases/latest, which is not what we want. Hard to know what to do here.
- [ ] `nimbus-fml` is downloaded per component (probably using the build directory). This may need a project.rootDir, and a clean task.
- [ ] Work out how to add the generated file to the classpath when generating an app services component file.

Once again, thanks for your hard work on this; let's get these bugs files and added to the epic, and then get this landed.

**Comment by jhugman** [comment]
In testing, I worked with these changes in the monorepo, and appservices.

[patch_nimbus_changes_focus_and_android_components.patch](https://github.com/mozilla/application-services/files/10405274/patch_nimbus_changes_focus_and_android_components.patch)
[patch_nimbus_in_appservices.patch](https://github.com/mozilla/application-services/files/10405275/patch_nimbus_in_appservices.patch)

**Pull request merged**
