### PR TITLE
Add docs on vendoring this repo into mozilla-central

### PR DESCRIPTION
**Pull request by mhammond**
Adding a doc to give an overview of how to vendor, and a place to add tips and tricks to make it easier.

### CODE REVIEW

**Comment by mhammond** [comment]
glandium has a great idea for simplifying this, which I'll do, and update this after it lands.

**Review by bendk — APPROVED** [review]
Looks great!

**Review by tarikeshaq — CHANGES_REQUESTED** [review]
Can we add a reference to the new doc in `docs/SUMMARY.md`? I tend to use ~~https://mozilla.github.io/uniffi-rs/~~ [mozilla.github.io/application-services/](https://mozilla.github.io/application-services/) for our docs 😬 

Edit wrong docs link 🤦

**Comment by mhammond** [comment]
I updated this to reflect what recently landed in m-c, which makes this entire process much simpler! I'm asking for re-review because it changed so much.

I also moved the doc to "howtos" and added a link to SUMMARY.md

**Review by bendk — APPROVED** [review]
The docs still look good and I really like how all the revisions are in 1 file with the new process.

**Review by skhamis — APPROVED** [review]
LGTM (Even though there's already 2 r+, going to approve so it's out of my Q)

**Pull request merged**
