### PR TITLE
New branch build system [firefox-android: main] [firefox-ios: main] [ci full]

### PR DESCRIPTION
**Pull request by bendk**
Instead of trying to run all the tests, let's just try to build the application.  This system will hopefully be simpler to maintain and also New branch build system.

We lose a little by not running the unit test, but we keep the main features of the branch build system: testing if there are unresolved breaking changes and giving devs/testers an APK to manually test

Don't merge yet, I'm using the PR to test out the new code.

### Pull Request checklist ###

- **Breaking changes**:  This PR follows our [breaking change policy](https://github.com/mozilla/application-services/blob/main/docs/howtos/breaking-changes.md)
  - [ ] This PR follows the breaking change policy:
     - This PR has no breaking API changes, or
     - There are corresponding PRs for our consumer applications that resolve the breaking changes and have been approved
- [ ] **Quality**: This PR builds and tests run cleanly
  - Note:
    - For changes that need extra cross-platform testing, consider adding `[ci full]` to the PR title.
    - If this pull request includes a breaking change, consider [cutting a new release](https://github.com/mozilla/application-services/blob/main/docs/howtos/cut-a-new-release.md) after merging.
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes a changelog entry in [CHANGELOG.md](../CHANGELOG.md) or an explanation of why it does not need one
  - Any breaking changes to Swift or Kotlin binding APIs are noted explicitly
- [ ] **Dependencies**: This PR follows our [dependency management guidelines](https://github.com/mozilla/application-services/blob/main/docs/dependency-management.md)
  - Any new dependencies are accompanied by a summary of the due dilligence applied in selecting them.

[Branch builds](https://github.com/mozilla/application-services/blob/main/docs/howtos/branch-builds.md): add `[firefox-android: branch-name]` to the PR title.

### CODE REVIEW

**Comment by bendk** [comment]
@sammy @tarikeshaq any idea what's going on with the firefox-ios build?  I think this is the relevant log portion:

```
[task 2023-07-03T19:54:45.083Z] + xcodebuild -resolvePackageDependencies
[task 2023-07-03T19:54:45.934Z] Command line invocation:
[task 2023-07-03T19:54:45.934Z]     /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -resolvePackageDependencies
[task 2023-07-03T19:54:45.934Z] 
[task 2023-07-03T19:54:47.933Z] Resolve Package Graph
[task 2023-07-03T19:54:48.109Z] 
[task 2023-07-03T19:54:48.109Z] Resolved source packages:
[task 2023-07-03T19:54:48.109Z]   BrowserKit: /var/opt/generic-worker/tasks/task_168841144184582/checkouts/vcs/firefox-ios/BrowserKit
[task 2023-07-03T19:54:48.109Z] 
[task 2023-07-03T19:54:48.109Z] xcodebuild: error: Could not resolve package dependencies:
[task 2023-07-03T19:54:48.109Z]   the tools version ' 5.6' is not valid; consider using '// swift-tools-version:5.3' to specify the current tools version
[task 2023-07-03T19:54:48.109Z] 
```

**Comment by bendk** [comment]
Thanks!  Looks like it's Xcode 12.2 and I think Swift 5.6 based on that error message.  I filed a bugzilla ticket to upgrade the versions.

**Comment by bendk** [comment]
@tarikeshaq I think this one is basically ready to land.  My one question is if there should be some extra artifacts published for the swift build task?  Like is there some sort of package for the build that someone could load in an ios emulator to manually test things?

**Review by tarikeshaq — APPROVED** [review]
A bit of a rubber stamp on the taskcluster bits, but thank you! This will be very impactful especially for iOS!

Do you think we should also run ci full on this one before landing as well?

**Pull request merged**
