### PR TITLE
Add nimbus update to cut-v74.0.0

### PR DESCRIPTION
**Pull request by travis79**

### CODE REVIEW

**Review by rfk — APPROVED** [review]
I'm trying to think whether we should re-order things here so that the commit that says "Cut release v74.0.0" is on top of the stack, but it probably doesn't matter.

**Comment by travis79** [comment]
> I'm trying to think whether we should re-order things here so that the commit that says "Cut release v74.0.0" is on top of the stack, but it probably doesn't matter.

Maybe I can squash and force push to the cut branch rather than PR?

**Comment by rfk** [comment]
> Maybe I can squash and force push to the cut branch rather than PR?

If you're happy to try that, that sounds good - I can stand by for r+ in the other PR (or, we can close that one and make a new one with your squashed commit)

**Comment by travis79** [comment]
Closing this in favor of just squashing this into #3943

**Pull request closed without merging**
