### PR TITLE
Xcode Megazord project

### PR DESCRIPTION
**Pull request by garvankeeley**
Prototype of what this might look like, the base branch is `swift-rc-log`.

- `String+Free.swift`  exists twice, this needed renaming
- `Errors.swift` same as above

### CODE REVIEW

**Comment by garvankeeley** [comment]
The xcode project itself contains all the files from Logins and FxAClient, nothing too fancy happening here:
screenshot 2019-02-05 16 22 17

**Comment by thomcc** [comment]
That's not good, I'll look into it after meetings. I wonder if the things we're doing to work around https://github.com/rust-lang/rust/issues/50007 don't work on iOS (when I checked before they seemed to, but hard to say)

**Comment by garvankeeley** [comment]
the "umbrella header" for cross lang linking isn't correctly specified, fixing it now

**Comment by garvankeeley** [comment]
All that is left is a minor issue with the `queue` being defined in both projects.
image

**Comment by garvankeeley** [comment]
In order to split up this WIP commit to the parts that are immediately landable, I did this PR
https://github.com/mozilla/application-services/pull/625

**Pull request closed without merging**
