### PR TITLE
Rename cleartext to payload in the bridged engine envelopes

### PR DESCRIPTION
**Pull request by mhammond**
Things like #5100 and the broader refactor to close the gap between "bridged engines" and normal sync engines would be a whole lot easier if the bridged-engine called its payload field "payload". I can't see a good reason to not make that change, and now seems a good time because only the webext-storage engine actually cares.

So I made this PR, and the matching [bug 1787688](https://bugzilla.mozilla.org/show_bug.cgi?id=1787688) - that bug also helps some of the tabs work.

### CODE REVIEW

**Review by skhamis — APPROVED** [review]
This is a great change with hardly any obvious drawbacks. LGTM 🚀

**Comment by skhamis** [comment]
(btw, the swiftlint is a circleci issue regarding an outdated mac runner) -- this should be fine to ignore, especially since this doesn't actually touch swift files

**Comment by mhammond** [comment]
> would be a whole lot easier if the bridged-engine called its payload field "payload".

I'm actually no longer sure that's true. It's more consistent, but I still need to spell out the payload explicitly for serde-flatten reasons.

**Review by bendk — APPROVED** [review]
Agree with this one as well, anything that brings the bridged engine and sync15-traits code closer together is good.

**Pull request merged**
