### PR TITLE
Strip `/1.0/sync/1.5` prefix if present in self-hosted tokenserver URL.

### PR DESCRIPTION
**Pull request by rfk**
Over in https://github.com/mozilla-services/docs/pull/89, a user noted that Firefox iOS differs from other clients when it comes to self-hosting - other clients expect you to provide the tokenserver url with `/1.0/sync/1.5` suffix, while Firefox iOS requires that you do not.

I think we should accept this known suffix and strip it if present, as a convenience for self-hosters.

### CODE REVIEW

**Comment by mhammond** [comment]
I'm a little surprised by this because we [theoretically allow either this suffix to exist or not](https://github.com/mozilla/application-services/blob/main/components/sync15/src/token.rs#L66).

**Comment by rfk** [comment]
Oh, huh. Thanks!

I was looking at the swift account manager code, which [unconditionally adds this prefix](https://github.com/mozilla/application-services/blob/0099443e9a3b7db4c246f843624d2b86f7b0a385/components/fxa-client/ios/FxAClient/FxAccountManager.swift#L282) before returning it to the application, so maybe that difference in behavior is what's causing the user-visible effect here. Seems like it may be worth consolidating so it's stripped in one place, rather than having to remember to conditionally add it everywhere it's used.

**Comment by rfk** [comment]
(Note that IIRC, the Firefox iOS app still has some parts that sync outside of the rust code, and hence does its own talking to tokenserver)

**Review by eoger — APPROVED** [review]
LGTM thanks

**Pull request merged**
