### PR TITLE
Update Android Components to 104.0.2

### PR DESCRIPTION
**Pull request by rvandermeulen**
Not sure what the implications are for being 10 releases behind are in practice, but this updates to the latest-available release at least.

### CODE REVIEW

**Comment by rvandermeulen** [comment]
https://firefox-ci-tc.services.mozilla.com/tasks/Ab-A5A08QFmvi-AS78A2jQ/runs/0/logs/public/logs/live.log
```
> Task :httpconfig:compileDebugKotlin FAILED
w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    /builds/worker/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.5.20/218b60e1d446d1e0a18bc7aa8663634b136fbcc5/kotlin-stdlib-jdk7-1.5.20.jar (version 1.5)
    /builds/worker/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.6.10/b8af3fe6f1ca88526914929add63cf5e7c5049af/kotlin-stdlib-1.6.10.jar (version 1.6)
    /builds/worker/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.6.10/c118700e3a33c8a0d9adc920e9dec0831171925/kotlin-stdlib-common-1.6.10.jar (version 1.6)
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath
e: warnings found and -Werror specified
```
Not sure what to do about this.

**Comment by lougeniaC64** [comment]
@tarikeshaq Should this include a bump of kotlin too? Also do you want this to be included in the release I'm about to cut or should this be in a separate release?

**Comment by tarikeshaq** [comment]
Looks like github auto assigned you for review @lougeniaC64  I didn't mean this as an urgency signal 😆  shouldn't be urgent in terms of the upcoming A-S release.

re: Kotlin bump, if AC is on a higher version then we should follow! I think it'll also make things easier for us regarding M1s (cc @skhamis)

**Comment by lougeniaC64** [comment]
> Looks like github auto assigned you for review @lougeniaC64 I didn't mean this as an urgency signal 😆 shouldn't be urgent in terms of the upcoming A-S release.
> 
> re: Kotlin bump, if AC is on a higher version then we should follow! I think it'll also make things easier for us regarding M1s (cc @skhamis)

**Comment by lougeniaC64** [comment]
Yikes! Sorry, didn't mean to close the PR. Just pushing buttons for reasons. 😖

**Comment by skhamis** [comment]
> Looks like github auto assigned you for review @lougeniaC64 I didn't mean this as an urgency signal 😆 shouldn't be urgent in terms of the upcoming A-S release.
> 
> re: Kotlin bump, if AC is on a higher version then we should follow! I think it'll also make things easier for us regarding M1s (cc @skhamis)

Yes this will be really nice to kick off a lot of M1 improvements for using native arm64 JDKs!



> https://firefox-ci-tc.services.mozilla.com/tasks/Ab-A5A08QFmvi-AS78A2jQ/runs/0/logs/public/logs/live.log
> 
> ```
> > Task :httpconfig:compileDebugKotlin FAILED
> w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
>     /builds/worker/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.5.20/218b60e1d446d1e0a18bc7aa8663634b136fbcc5/kotlin-stdlib-jdk7-1.5.20.jar (version 1.5)
>     /builds/worker/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.6.10/b8af3fe6f1ca88526914929add63cf5e7c5049af/kotlin-stdlib-1.6.10.jar (version 1.6)
>     /builds/worker/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.6.10/c118700e3a33c8a0d9adc920e9dec0831171925/kotlin-stdlib-common-1.6.10.jar (version 1.6)
> w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath
> e: warnings found and -Werror specified
> ```
> 
> Not sure what to do about this in the short term. I guess the issue is that AC is on Kotlin 1.6 now but A-S is still on 1.5.

@rvandermeulen we'll also need to bump the kotlin version in `build.gradle` here, that might solve the build issues (contingent we didn't have any breaking changes to take care of):
 https://github.com/mozilla/application-services/blob/main/build.gradle#L6
```
    ext {
        kotlin_version = '1.5.20'
        kotlin_coroutines_version = '1.5.0'
```

**Comment by rvandermeulen** [comment]
I'll try bumping it and see what happens. I can't commit to trying to fix any bustage should the need arise, however 😄.

**Comment by skhamis** [comment]
> I'll try bumping it and see what happens. I can't commit to trying to fix any bustage should the need arise, however 😄.

hah, totally understand! If it does indeed break -- we'll be happy to commandeer this and see it to the end, we definitely appreciate bringing this to light! (10 releases behind is not somewhere we wanna be -- even for testing)

**Comment by skhamis** [comment]
Since Circle CI didn't run, going to to test closing/opening

**Review by skhamis — APPROVED** [review]
Nice! Thanks for updating this. LGTM 🚀

**Pull request merged**
