### PR TITLE
Update docs for building this repo

### LINKED ISSUE #5414: Help building on Fedora
I'm trying to build the project - at least running the test suite - on Fedora. I followed [the steps](https://github.com/mozilla/application-services/blob/main/docs/building.md#linux) and I get a `NoNssDir` error:

```sh
$ RUST_BACKTRACE=1 cargo test
   Compiling this and that...
   Compiling num-traits v0.2.15
error: failed to run custom build command for `nss_sys v0.1.0 (/home/jo/git/application-services/components/support/rc_crypto/nss/nss_sys)`

Caused by:
  process didn't exit successfully: `/home/jo/git/application-services/target/debug/build/nss_sys-eddc484f54a37c61/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=NSS_DIR

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NoNssDir', components/support/rc_crypto/nss/nss_sys/build.rs:6:34
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:575:5
     1: core::panicking::panic_fmt
               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:65:14
     2: core::result::unwrap_failed
               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/result.rs:1791:5
     3: core::result::Result<T,E>::unwrap
               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/result.rs:1113:23
     4: build_script_build::main
               at ./build.rs:6:5
     5: core::ops::function::FnOnce::call_once
               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/ops/function.rs:251:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I have searched through the NSS docs but was not able to find any hint.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3634)

### PR DESCRIPTION
**Pull request by mhammond**
Fixes #5414 - @jo how does this look to you?

### CODE REVIEW

**Comment by jo** [comment]
Thanks!

I think it should also mention `libxcb-devel`, I needed to install it in order to be able to run the tests

**Comment by jo** [comment]
One little formatting thing: imo a [part with headings inside a list](https://github.com/mozilla/application-services/blob/33155a42508764c7ebb6fa4e1b3c06552226738a/docs/building.md#linux) should better be avoided, otherwise one thinks the list ends.

**Comment by mhammond** [comment]
> I think it should also mention `libxcb-devel`, I needed to install it in order to be able to run the tests

I (hopefuuly!) killed that in #5443

**Comment by mhammond** [comment]
> One little formatting thing: imo a [part with headings inside a list](https://github.com/mozilla/application-services/blob/33155a42508764c7ebb6fa4e1b3c06552226738a/docs/building.md#linux) should better be avoided, otherwise one thinks the list ends.

Yeah, I agree, but not sure how to resolve it here - I think we should take my change and leave the larger refactor to later.

**Review by bendk — APPROVED** [review]
LGTM

**Pull request merged**
