### PR TITLE
Update Gradle to version 7.6.1 and Android Gradle Plugin to 7.4.1

### PR DESCRIPTION
**Pull request by rvandermeulen**
### Pull Request checklist ###

- [ ] **Quality**: This PR builds and tests run cleanly
  - Note:
    - For changes that need extra cross-platform testing, consider adding `[ci full]` to the PR title.
    - If this pull request includes a breaking change, consider [cutting a new release](https://github.com/mozilla/application-services/blob/main/docs/howtos/cut-a-new-release.md) after merging.
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes a changelog entry in [CHANGES_UNRELEASED.md](../CHANGES_UNRELEASED.md) or an explanation of why it does not need one
  - Any breaking changes to Swift or Kotlin binding APIs are noted explicitly
- [ ] **Dependencies**: This PR follows our [dependency management guidelines](https://github.com/mozilla/application-services/blob/main/docs/dependency-management.md)
  - Any new dependencies are accompanied by a summary of the due dilligence applied in selecting them.

[Branch builds](https://github.com/mozilla/application-services/blob/main/docs/howtos/branch-builds.md): add `[ff-android: firefox-android-branch-name]` and/or `[fenix: fenix-branch-name]` to the PR title.

### CODE REVIEW

**Comment by rvandermeulen** [comment]
This looks good AFAICT. The only CI bustage is broken Fenix builds due to #5406. That said, I must confess that I don't claim to fully understand the implications of the JVM 11 bytecode change even if everything does appear to be green.

**Review by jeddai — APPROVED** [review]
r+wc If Fenix+Focus are updated to this version as well I don't see a problem with upgrading it. 

I would request though that we add a changelog entry as a breaking change noting that the jvm compat target is now 11

**Review by travis79 — APPROVED** [review]
Looks good to me, with @jeddai's request to add a changelog entry satisfied.

**Comment by rvandermeulen** [comment]
AC/Fenix/Focus bump has landed in https://github.com/mozilla-mobile/firefox-android/pull/732.

**Pull request merged**
