### PR TITLE
Properly support Taskcluster actions in .taskcluster.yml

### PR DESCRIPTION
**Pull request by ahal**
It turns out that the `.taskcluster.yml` was not set up to support actions (like rerun or cancel). This PR adjusts that. It is a CI-only change and therefore does not contain tests or entry in the changelog.

### Pull Request checklist ###

- [ x ] **Quality**: This PR builds and tests run cleanly
  - Note:
    - For changes that need extra cross-platform testing, consider adding `[ci full]` to the PR title.
    - If this pull request includes a breaking change, consider [cutting a new release](https://github.com/mozilla/application-services/blob/main/docs/howtos/cut-a-new-release.md) after merging.
- [ x ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ x ] **Changelog**: This PR includes a changelog entry in [CHANGES_UNRELEASED.md](../CHANGES_UNRELEASED.md) or an explanation of why it does not need one
  - Any breaking changes to Swift or Kotlin binding APIs are noted explicitly
- [ x ] **Dependencies**: This PR follows our [dependency management guidelines](https://github.com/mozilla/application-services/blob/main/docs/dependency-management.md)
  - Any new dependencies are accompanied by a summary of the due dilligence applied in selecting them.

[Branch builds](https://github.com/mozilla/application-services/blob/main/docs/howtos/branch-builds.md): add `[ac: android-components-branch-name]` and/or `[fenix: fenix-branch-name]` to the PR title.

### CODE REVIEW

**Comment by ahal** [comment]
Unforunately because of how hooks work, I'll need to land this, re-run ci-admin and then test that it works. So there may be another iteration here.

**Comment by ahal** [comment]
@tarikeshaq I don't have collaborator on this repo, but could you add the `mozilla/releng` team as an additional reviewer here? Thanks in advance!

**Review by escapewindow — APPROVED** [review]

**Comment by escapewindow** [comment]
We'll need a ci-admin run after this lands to enable the hooks.

**Comment by tarikeshaq** [comment]
Hmm closing and re-opening, not sure why circle ci didn't run here

**Review by tarikeshaq — APPROVED** [review]
Rubber stamp, but looks good to me!

**Pull request merged**
