### PR TITLE
Add a [ci skip] flag to skip CI

### LINKED ISSUE #266: taskcluster: Do not run for commits that include [ci skip]
This is the `a-s` equivalent of https://github.com/mozilla-mobile/android-components/issues/641.  I'd like to keep our automation as consistent as possible but I do wish this was more centralized!

### PR DESCRIPTION
**Pull request by eoger**
Fixes #266

### CODE REVIEW

**Comment by thomcc** [comment]
I thought we already had this, or does it not work

**Comment by eoger** [comment]
Maybe we've had it in the past?

**Comment by eoger** [comment]
> Should we allow [skip ci] (and [full ci]), too, to match CircleCI?

I believe they work on the commit title in Circle, which is unfortunate :/

**Comment by linacambridge** [comment]
Ugh, right, I forgot. 😞 It'd be so nice if we could use the PR title there, too! Oh, well.

**Pull request merged**
