### PR TITLE
Update the Rust version [full ci]

### PR DESCRIPTION
**Pull request by bendk**
This matches the estimated "uses" value for 119.  The MSRV has not been set, so let's keep it at the 1.66 version from 116.

- https://github.com/mozilla/application-services/blob/main/docs/design/rust-versions.md
- https://firefox-source-docs.mozilla.org/writing-rust-code/update-policy.html

In addition to keeping up with the changes, I think this should fix the rustdoc build issues.

### Pull Request checklist ###

- **Breaking changes**:  This PR follows our [breaking change policy](https://github.com/mozilla/application-services/blob/main/docs/howtos/breaking-changes.md)
  - [ ] This PR follows the breaking change policy:
     - This PR has no breaking API changes, or
     - There are corresponding PRs for our consumer applications that resolve the breaking changes and have been approved
- [ ] **Quality**: This PR builds and tests run cleanly
  - Note:
    - For changes that need extra cross-platform testing, consider adding `[ci full]` to the PR title.
    - If this pull request includes a breaking change, consider [cutting a new release](https://github.com/mozilla/application-services/blob/main/docs/howtos/cut-a-new-release.md) after merging.
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes a changelog entry in [CHANGELOG.md](../CHANGELOG.md) or an explanation of why it does not need one
  - Any breaking changes to Swift or Kotlin binding APIs are noted explicitly
- [ ] **Dependencies**: This PR follows our [dependency management guidelines](https://github.com/mozilla/application-services/blob/main/docs/dependency-management.md)
  - Any new dependencies are accompanied by a summary of the due dilligence applied in selecting them.

[Branch builds](https://github.com/mozilla/application-services/blob/main/docs/howtos/branch-builds.md): add `[firefox-android: branch-name]` to the PR title.

### CODE REVIEW

**Review by tarikeshaq — APPROVED** [review]
This looks good once the ci is passing, is this worth a `[ci full]` too?

**Comment by bendk** [comment]
> This looks good once the ci is passing, is this worth a `[ci full]` too?

Sounds good to me, added the tag.  Can you double-check my fixes for clippy?

**Comment by tarikeshaq** [comment]
> Maybe we should update those min-supported-version tests to not run trybuil

If we can do that, it would be best - I'm not surprised the error messages are different and we'd probably come across this again in the future.

Another more extreme option is to limit the `min-supported-version` to build but not test, but that might be a change to our policy so we should review that

**Review by tarikeshaq — APPROVED** [review]
Clippy changes look good! Thank you for fixing the minimum rust version tests too! 🚢

**Pull request merged**
