### PR TITLE
Suggest benchmark updates

### PR DESCRIPTION
**Pull request by bendk**
I used this to benchmark the Fakespot prefix settings.  Results of that will be shared in another PR, but I wanted to push the benchmark updates separately

Added fakespot query benchmark.  Generalized some things so that code can be shared between the ingest and query benchmarks and also so that it will be easy to add more query bechmarks.

Added Fakespot ingest benchmarks.  Re-organized the list so that the ingest and ingest-again benchmarks are next to each other.  This makes it easier to add benchmarks for a new suggestion type.

### Pull Request checklist ###

- **Breaking changes**:  This PR follows our [breaking change policy](https://github.com/mozilla/application-services/blob/main/docs/howtos/breaking-changes.md)
  - [ ] This PR follows the breaking change policy:
     - This PR has no breaking API changes, or
     - There are corresponding PRs for our consumer applications that resolve the breaking changes and have been approved
- [ ] **Quality**: This PR builds and tests run cleanly
  - Note:
    - For changes that need extra cross-platform testing, consider adding `[ci full]` to the PR title.
    - If this pull request includes a breaking change, consider [cutting a new release](https://github.com/mozilla/application-services/blob/main/docs/howtos/cut-a-new-release.md) after merging.
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes a changelog entry in [CHANGELOG.md](../CHANGELOG.md) or an explanation of why it does not need one
  - Any breaking changes to Swift or Kotlin binding APIs are noted explicitly
- [ ] **Dependencies**: This PR follows our [dependency management guidelines](https://github.com/mozilla/application-services/blob/main/docs/dependency-management.md)
  - Any new dependencies are accompanied by a summary of the due diligence applied in selecting them.

[Branch builds](https://github.com/mozilla/application-services/blob/main/docs/howtos/branch-builds.md): add `[firefox-android: branch-name]` to the PR title.

### CODE REVIEW

**Comment by bendk** [comment]
After thinking through this a bit more, I want to make a couple other changes.  You may want to hold-off on reviewing this one.

**Comment by bendk** [comment]
This is ready for review now.

**Review by ncloudioj — APPROVED** [review]
Nice additions, thanks!

**Comment by bendk** [comment]
This doesn't change any dependencies, so I'm going to merge despite the dependency check CI issue.

**Pull request merged**
