### PR TITLE
Don't use the codecov bash uploader

### PR DESCRIPTION
**Pull request by bendk**
### Pull Request checklist ###

- [x] **Quality**: This PR builds and tests run cleanly
  - Note:
    - For changes that need extra cross-platform testing, consider adding `[ci full]` to the PR title.
    - If this pull request includes a breaking change, consider [cutting a new release](https://github.com/mozilla/application-services/blob/main/docs/howtos/cut-a-new-release.md) after merging.
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes a changelog entry in [CHANGES_UNRELEASED.md](../CHANGES_UNRELEASED.md) or an explanation of why it does not need one
  - Any breaking changes to Swift or Kotlin binding APIs are noted explicitly
- [x] **Dependencies**: This PR follows our [dependency management guidelines](https://github.com/mozilla/application-services/blob/main/docs/dependency-management.md)
  - Any new dependencies are accompanied by a summary of the due dilligence applied in selecting them.

### CODE REVIEW

**Comment by bendk** [comment]
Interestingly, I just got an email from codecov introducing their new uploader: https://about.codecov.io/blog/introducing-codecovs-new-uploader/.

We could use that, but it seems simple enough to use this bash script.  I guess it comes down to how much you trust codecov at this point.

**Review by mhammond — COMMENTED** [review]
This seems extremely simple - the existing bash loader seems to also run `sed` over the reports and does various other things, like checking the coverage file actually exists, etc - are we sure they are not necessary?

It also seems this PR apparently failed to generate coverage info, which seems odd.

I also got their security email and it had [a link](https://about.codecov.io/blog/validating-the-bash-script-on-ci) to a better way to validate the bash script - which still isn't ideal. I think other teams here also just vendored the bash script in, which is safe as long as the script is audited every time it is updated, which seems unlikely tbh :)

But I've no objections to running with this if it works, but I'd like to understand why there's no coverage for this PR before hitting the "approve" button.

**Comment by mhammond** [comment]
> I'd like to understand why there's no coverage for this PR before hitting the "approve" button.

hrm - I see that for some other PRs too :(

**Comment by bendk** [comment]
That uploader script does so much, it's really hard to understand it.  My general approach was to extract what seemed like the core functionality and if the reports worked then assume the rest wasn't needed.  I see a bunch of sed/awk code around line 1556, but that seems to only run for `.gcov` files.

I'm not exactly sure what happened with the coverage diff.  The commit that it's trying to compare to seems correct though.  When I go to the commit list (https://app.codecov.io/gh/mozilla/application-services/commits) I can see the commit (`367280a`) and it's just listed as processing.  Seems like that's a separate, hopefully temporary, issue.

**Review by mhammond — APPROVED** [review]
SGTM and it's easy to change our mind later.

**Pull request merged**
