### PR TITLE
Cut v63.0.0

### LINKED ISSUE #3564: Cut a new release with glean in the iOS megazord
So that firefox-ios can get the changes from https://github.com/mozilla/application-services/pull/3554

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1757)
┆Story Points: 3
┆Sprint: SYNC - end 2020-09-11

### PR DESCRIPTION
**Pull request by rfk**
Fixes #3564.

### CODE REVIEW

**Comment by mhammond** [comment]
Any chance of waiting for #3567? I suspect we can get that landed in first thing in the (.au) morning...

**Comment by rfk** [comment]
Alrighty, rebased atop latest master.

**Review by mhammond — APPROVED** [review]
👍

**Pull request merged**
