### PR TITLE
Store i64 in sync15::ServerTimestamp

### PR DESCRIPTION
**Pull request by lyuyuan92**
Store an i64 instead of f64 in sync15::ServerTimestamp.
Issue #815

### CODE REVIEW

**Comment by lyuyuan92** [comment]
@thomcc @mhammond Hi! I have updated my branch for #815. Please let me know if anything needs to be changed/updated. Thanks!

**Comment by thomcc** [comment]
Ah, sorry, it looks like this fails the integration tests. These require a bit more setup to run (you need to have `node` installed), but can be run with `cargo run -p sync-test`.

**Comment by lyuyuan92** [comment]
@thomcc Hi! The failure likely happens at [this line](https://github.com/mozilla/application-services/blob/a232841ecb42383ad7c5440a0c7b31283b28aac2/components/sync15/src/client.rs#L225). The `resp` contains float number timestamps. To fix this, should I implement `Deserialize` and `Serialize` traits for ServerTimestamp? Thanks!

**Comment by thomcc** [comment]
It's not a few lines down at https://github.com/mozilla/application-services/blob/a232841ecb42383ad7c5440a0c7b31283b28aac2/components/sync15/src/client.rs#L229?

**Comment by lyuyuan92** [comment]
Error message says: "Error synchronizing: JSON error: invalid type: floating point `1558664137.2`, expected i64 at line 1 column 22)".

**Comment by thomcc** [comment]
Yes, you're correct, I edited my comment, but you'll need to implement those traits.

**Comment by lyuyuan92** [comment]
Please re-review, thanks!

**Comment by thomcc** [comment]
(I'll merge this early next week in case there's some other issue requiring a backout. Which seems really unlikely, but still, I don't want to work over the weekend)

**Pull request merged**
