### PR TITLE
Bumping UniFFI to 0.27.0 [ci full]

### PR DESCRIPTION
**Pull request by bendk**
Pushing out so I can see if the CI is green.  Let's not merge this until there's a Glean release that does the same thing

### Pull Request checklist ###

- **Breaking changes**:  This PR follows our [breaking change policy](https://github.com/mozilla/application-services/blob/main/docs/howtos/breaking-changes.md)
  - [ ] This PR follows the breaking change policy:
     - This PR has no breaking API changes, or
     - There are corresponding PRs for our consumer applications that resolve the breaking changes and have been approved
- [ ] **Quality**: This PR builds and tests run cleanly
  - Note:
    - For changes that need extra cross-platform testing, consider adding `[ci full]` to the PR title.
    - If this pull request includes a breaking change, consider [cutting a new release](https://github.com/mozilla/application-services/blob/main/docs/howtos/cut-a-new-release.md) after merging.
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes a changelog entry in [CHANGELOG.md](../CHANGELOG.md) or an explanation of why it does not need one
  - Any breaking changes to Swift or Kotlin binding APIs are noted explicitly
- [ ] **Dependencies**: This PR follows our [dependency management guidelines](https://github.com/mozilla/application-services/blob/main/docs/dependency-management.md)
  - Any new dependencies are accompanied by a summary of the due dilligence applied in selecting them.

[Branch builds](https://github.com/mozilla/application-services/blob/main/docs/howtos/branch-builds.md): add `[firefox-android: branch-name]` to the PR title.

### CODE REVIEW

**Comment by badboy** [comment]
Glean release happening tomorrow.

**Comment by bendk** [comment]
Updated to use the new Glean release.  This should be ready to merge now and that will unblock taking the changes in moz-central.

**Comment by bendk** [comment]
Actually, this is not ready.  I need to fix the build issues with ios and android.

**Comment by bendk** [comment]
I think this is working except for iOS/Swift can anyone help me out there?  I believe it's related to the changes to RustBuffer that makes the `capacity` and `len` fields `u64` instead of `i32`.   But I have no clue how that's breaking the build.

**Review by rvandermeulen — CHANGES_REQUESTED** [review]
I would have expected to also see changes to `gradle/libs.versions.toml`, `megazords/ios-rust/MozillaTestServices/MozillaTestServices.xcodeproj/project.pbxproj`, and `megazords/ios-rust/MozillaTestServices/MozillaTestServices.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved` for the Glean part of this.

Here's the previous bump PR for reference:
https://github.com/mozilla/application-services/pull/6163/files

**Comment by tarikeshaq** [comment]
@bendk applying the changes that @rvandermeulen pointed out could fix your iOS issue, the tests are using an older glean - and looks like there is a mismatch in the shape of `RustBuffer` based on that causing issues

**Comment by badboy** [comment]
Hah, the iOS issue seems to be what a user reported as well: https://github.com/mozilla/uniffi-rs/issues/2058

**Review by rvandermeulen — APPROVED** [review]
LGTM for the comments I left.

**Review by badboy — APPROVED** [review]

**Pull request merged**
